Klisin lab2
NikitkoCent/engnr-nsu-cpp-2021 pull request #11
Opened 2021-11-19 09:54 UTC by liskiran

2021-12-03 01:41 UTC, NikitkoCent commented
Пожалуйста, переподключите все используемые сторонние библиотеки либо с помощью подмодулей git (https://git-scm.com/book/ru/v2/Инструменты-Git-Подмодули) либо с помощью vcpkg.

Исходные файлы используемых библиотек должны пропасть из PR:
![](https://user-images.githubusercontent.com/6972448/141604013-7c9ed2ab-c300-4112-9524-e3db70ffcb34.png)

2021-12-03 01:56 UTC, NikitkoCent commented
Есть исходники с тестами, но нет исходников программы, которая описывается в тексте лабораторной.

2021-12-03 01:57 UTC, NikitkoCent commented
`README.md` не заполнен.

2021-12-03 02:02 UTC, NikitkoCent requested changes

2021-12-03 02:02 UTC, NikitkoCent commented on 2/Calculator.h
> +    class Calculator {
Текущая архитектура калькулятора не использует шаблон проектирования "Фабричный метод", необходимость использования которого указано в требованиях лабораторной.

2021-12-16 18:02 UTC, liskiran commented on 2/Calculator.h
> +    class Calculator {
Поправил

2021-12-17 08:26 UTC, liskiran commented on 2/Calculator.h
> +    class Calculator {
А можете сказать как правильно передать путь к тестам? А то у меня googletest не работает.

2021-12-17 08:59 UTC, liskiran commented on 2/Calculator.h
> +    class Calculator {
ладно, я обошелся без этого

2021-12-18 14:23 UTC, NikitkoCent commented
> `2/README.md` не заполнен (информация о программе и инструкции по сборке)

все еще не исправлено

2021-12-18 14:59 UTC, NikitkoCent requested changes
8 замечаний/вопросов

2021-12-18 14:59 UTC, NikitkoCent commented on 2/Calculator.h
> +    virtual void exec(const std::vector<std::string> &tokens,
Не соблюдено требование из методических указаний к лабораторной:
>Содержимое стека и список (лучше ассоциативный контейнер) определенных именованных параметров передавать команде в виде специального объекта — контекста исполнения;

2021-12-18 14:59 UTC, NikitkoCent commented on 2/Calculator.h
> +bool is_number(const std::string &line) {
Пожалуйста, разделите объявление и определение функций/методов по заголовочным и `.cpp` файлам соответственно.

2021-12-18 14:59 UTC, NikitkoCent commented on 2/Calculator.h
> +        values.push(second_element + first_element);
Если вы хотите сдавать 2-ую часть лабораторной, внимательно прочитайте, о чем она, и для чего она предлагает использовать `SafeInt`

2021-12-18 14:59 UTC, NikitkoCent commented on 2/Calculator.h
> +        values.push(second_element + first_element);
P.S. возможно, понадобится отдельно обработать случай команды Abs.

2021-12-18 14:59 UTC, NikitkoCent commented on 2/Calculator.h
> +            values.push(names_and_values[varname]);
Сколько раз в этой ветке else выполняется поиск внутри names_and_values? Можно ли сократить это количество до 1?

2021-12-18 14:59 UTC, NikitkoCent commented on 2/Calculator.h
> +        std::string varname = tokens[1];
1. Что будет, если `tokens.size() < 2`?
2. Добавьте тест на такой случай

2021-12-18 14:59 UTC, NikitkoCent commented on 2/Calculator.h
> +class Abs : public Command {
Добавьте тест примерно такого содержания:
```
PUSH -9223372036854775808
ABS
PRINT
```

Ожидается, что программа выбросит исключение целочисленного переполнения.

2021-12-18 14:59 UTC, NikitkoCent commented on 2/Calculator.h
> +        int value = std::stoi(tokens[1]);
std::stoi возвращает `int`, а вы работаете с `int64_t`; эти типы обычно не совпадают. Посмотрите в сторону [std::from_chars](https://en.cppreference.com/w/cpp/utility/from_chars)

2021-12-18 15:28 UTC, liskiran commented on 2/Calculator.h
> +        std::string varname = tokens[1];
ну тогда будет ошибка, так как мы не передаем название переменной в которую перемещаем верхнее значение стека.
(добавлю тест)

2021-12-18 17:55 UTC, liskiran commented on 2/Calculator.h
> +            values.push(names_and_values[varname]);
так тут 1 раз и выполняется поиск, потом если нашелся элемент, то происходит push, а если не нашел то ошибка вызывается

2021-12-21 10:26 UTC, liskiran commented on 2/Calculator.h
> +        int value = std::stoi(tokens[1]);
я решил заменить на std::stoll он возвращает int64_t

2021-12-21 10:29 UTC, liskiran commented on 2/Calculator.h
> +class Abs : public Command {
std::stoll должен отлавливать такую ошибку

2021-12-21 11:18 UTC, liskiran commented on 2/Calculator.h
> +bool is_number(const std::string &line) {
я попытался это сделать но мне высвечивалась подобная ошибка https://stackoverflow.com/questions/3065154/undefined-reference-to-vtable
и у меня не получилось решить эту проблему

2021-12-21 12:49 UTC, NikitkoCent commented on 2/Calculator.h
> +class Abs : public Command {
Это никак не связано с std::stoll. `-9223372036854775808` является минимальным значением, которое могут принимать `int64_t` объекты. Дело в том, что модуль этого числа (= `9223372036854775808`) ровно на единицу превышает максимальное значение `int64_t`, т.е. здесь будет переполнение.

Пруф: https://godbolt.org/z/r4jrW6z98

2021-12-21 13:12 UTC, liskiran commented on 2/Calculator.h
> +    virtual void exec(const std::vector<std::string> &tokens,
я засунул все в структуру

2021-12-21 14:52 UTC, liskiran commented on 2/Calculator.h
> +class Abs : public Command {
![image](https://user-images.githubusercontent.com/52342496/146949827-d2674a88-5f90-4843-b777-f6f093d6b3e7.png)
вроде ловится ошибка

2021-12-21 16:58 UTC, NikitkoCent commented on 2/Calculator.h
> +bool is_number(const std::string &line) {
Есть вариант кода с этой ошибкой? Пока не увижу, не смогу помочь, ошибка достаточно пространная.

2021-12-21 16:58 UTC, NikitkoCent commented on 2/Calculator.h
> +    virtual void exec(const std::vector<std::string> &tokens,
Где?

2021-12-21 17:09 UTC, liskiran commented on 2/Calculator.h
> +    virtual void exec(const std::vector<std::string> &tokens,
![image](https://user-images.githubusercontent.com/52342496/146970575-4ba89d39-533f-411d-9211-c114e9959285.png)

2021-12-22 14:08 UTC, NikitkoCent requested changes
5 замечаний/вопросов. После исправления можете приходить на этап устной сдачи.

2021-12-22 14:08 UTC, OnePatchGuy commented on 2/Calculator.h
> +class Abs : public Command {
Ну тест в любом случае добавьте. Можно воспользоваться `EXPECT_THROW`.

2021-12-22 14:08 UTC, OnePatchGuy commented on 2/Calculator.h
> +                      int args) = 0;
Для чего нужен параметр `args`? Не вижу, чтобы он хоть где-то использовался.

2021-12-22 14:08 UTC, OnePatchGuy commented on 2/README.md
> +Стековый калькулятор.
Нет инструкций по сборке

2021-12-22 14:08 UTC, NikitkoCent commented on 2/command_processing.h
> +void command_processing(std::stringstream& in_s, std::ifstream& in, int args) {
Реализацию этой функции также следует разделить между `.h` и `.cpp`

2021-12-22 14:08 UTC, NikitkoCent commented on 2/tests/CMakeFiles/generate.stamp
> +# CMake generation timestamp file for this directory.
Удалите все лишние файлы, не относящиеся к решению лабораторной. Можно воспользоваться `git rm --cached`

2021-12-22 19:47 UTC, NikitkoCent approved these changes
Вопросов/замечаний по коду больше нет.

2021-12-23 11:21 UTC, NikitkoCent commented
Лабораторная сдана; полный балл.

2021-12-23 11:21 UTC, closed without merging