Lkrazer lab3
NikitkoCent/engnr-nsu-cpp-2021 pull request #14
Opened 2021-11-22 05:31 UTC by Krazerleo

2021-12-15 20:53 UTC, NikitkoCent requested changes
1. 62 вопроса/замечания
2. Нужно починить сборку под Windows
  2.1. Для MSVC нужно не добавлять флаг компиляции `-fno-omit-frame-pointer`;
  2.2. См. лог сборки.

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/.vscode/launch.json
> +{
Директория .vscode содержит файлы с настройками IDE.

Эти файлы не относятся к исходному коду решения лабораторной, поэтому их в PR быть не должно.

Чтобы удалить директорию из репозитория, но удалять с компьютера, можете воспользоваться командой `git rm --cached`

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/CMakeLists.txt
> +FetchContent_MakeAvailable(googletest)
Эта функция требует CMake версии >=3.14.7. Пожалуйста, отобразите это в `cmake_minimum_required`

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/CMakeLists.txt
> +set (CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -fno-omit-frame-pointer -fsanitize=address")
Это на сегодняшний день нерекомендуемый способ установки флагов компиляции и линковки. Пожалуйста, воспользуйтесь `target_compile_options` и `target_link_options` (не забудьте про оба ваших таргета)

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/LinkedList_tests.cpp
> +    LinkedList<int> li1 = li;
Это вызов не копирующего присваивания, а конструктора копирования. Операторы присваивания работают тогда, когда объект _уже_ создан (сконструирован).

Можно просто сделать так:
```cpp
// default constructor
LinkedList<int> li1;

// copy-assignment
li1 = li;
```

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/LinkedList_tests.cpp
> +    LinkedList<int> list1 = std::move(list);
Нужно исправить по аналогии с копирующим присваиванием.

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/LinkedList_tests.cpp
> +    LinkedList<int> list2 = {1, 3, 4, 2, 3, 4, 5};
Метод insert должен вставлять значения _**перед**_ значением, на который указывает переданный итератор (`it2` в данном случае). Т.е. нужно ожидать, что `list1` примет вид `{3, 4, 1, 2, 3, 4, 5}`

Не забудьте проверить другие перегрузки `insert` на соответствие этой логике

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/src/linked_list.tpp
> +        pop_back();
Это некорректное поведение, т.к. итератор end() фактически не указывает на "реальный" элемент списка. Когда пользователь хочет удалить последний элемент, ему следует писать:
```cpp
list.pop_back();

// или 

list.erase(--list.end());
```

Подразумевается, что вызов erase от `past-the-end` итератора - это `undefined behaviour`

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/LinkedList_tests.cpp
> +    list3.erase(it3);
Не забудьте поправить тест здесь после исправления замечания в реализации метода `erase`

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/LinkedList_tests.cpp
> +
Добавьте сюда (или лучше вынесите в новый тест) случай, когда в insert передали итераторы, указывающие на один и тот же элемент - ожидается, что ничего не удалится:
<img width="628" alt="image" src="https://user-images.githubusercontent.com/6972448/146173905-6f858dcc-f245-4e62-88ec-96e0b9cee60f.png">

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/inc/linked_list.h
> +            if (&other == this)
В конструкторе такая ситуация невозможна - только в операторах присваивания. Подумайте почему.

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/inc/linked_list.h
> +            for (auto item : other)
Тут следует использовать ссылку, иначе сначала произойдет копирование сначала в item, а затем из item внутрь push_back:
```cpp
for (auto& item : other)

или

for (const auto& item : other)
```

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/LinkedList_tests.cpp
> +    list.sort();
Добавьте также тест на сортировку в порядке убывания. Для этого нужно воспользоваться второй перегрузкой `sort`, принимающей кастомный компаратор.

P.S. проще всего это будет сделать с помощью лямбды:
```cpp
[](const auto& left, const auto& right) { return left > right; }
```

Или, с помощью `std::greater`:
```cpp
std::greater<int>{}
```

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/LinkedList_tests.cpp
> +TEST(LL_Test, Remove_Test)
Добавьте тест на метод `remove_if`.

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/inc/node.h
> +        explicit Node(T &&_data) : BaseNode<T>{}, data(std::forward<T &&>(_data)) {}
В контексте конструктора `T&&` не является универсальной ссылкой, а лишь rvalue-ссылкой на T. В общем, вместо `std::forward` нужно использовать `std::move`, иначе у вас здесь будет копия вместо перемещения.

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/inc/linked_list.h
> +        LinkedList() : count(0), head(new BaseNode<T>()), tail(new BaseNode<T>())
Почему часть методов реализовано здесь (в `.h`), а часть - в `.tpp`? Для однородности предлагаю перенести всё иди туда, или сюда

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/inc/linked_list.h
> +        using reference = BaseNode<T> &;
`[const_]reference` и `[const_]pointer` должны быть ссылками/указателями не на внутренние структуры контейнера, а на используемый тип данных. В общем `T&` и `T*`.

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/inc/linked_list.h
> +        using size_type = std::int16_t;
1. Почему это знаковый тип данных? Размер списка никогда не может быть отрицательным числом.
2. При использовании 16-битного `int` максимальный размер списка будет 2^16 (~65 тыс.). Почему бы не увеличить битность?

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/inc/linked_list.h
> +        std::int16_t count;
Лучше воспользоваться уже определенным псевдонимом `size_type`, чтобы не допустить расхождений.

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/inc/linked_list.h
> +        LinkedList() : count(0), head(new BaseNode<T>()), tail(new BaseNode<T>())
Насчет `head` и `tail`: зачем они хранятся в виде указателей? Если их хранить по значению, тогда не понадобится для их инициализации использовать медленную (`new` + `delete`) динамическую память.

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/inc/linked_list.h
> +        reference front() { return *(head); }
Метод должен возвращать ссылку на первый "реальный" элемент списка (подразумевается, что вызов этого метода на пустом списке - `undefined behaviour`)

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/inc/linked_list.h
> +        reference back() { return *(tail); }
Метод должен возвращать ссылку на последний "реальный" элемент списка (подразумевается, что вызов этого метода на пустом списке - `undefined behaviour`)

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/inc/linked_list.h
> +            for (; first != last; first++)
Эффективнее ли будет здесь и во всех других местах использовать пре-инкремент итератора вместо пост-инкремента? Почему?

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/inc/linked_list.h
> +            for (auto item : init)
Тут следует использовать ссылку, иначе сначала произойдет копирование сначала в item, а затем из item внутрь push_back:
```cpp
for (auto& item : init)

или

for (const auto& item : init)
```

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/inc/linked_list.h
> +        void push_front();
Такой перегрузки не было в задании. С точки зрения пользователя совсем не очевидно, что она вставляет в список.

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/inc/linked_list.h
> +        void push_back();
Такой перегрузки не было в задании. С точки зрения пользователя совсем не очевидно, что она вставляет в список.

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/inc/linked_list.h
> +            for (int i = 0; i <= count; i++)
Чтобы избежать несовместимости типов, лучше вместо `int` использовать `size_type`.

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/inc/linked_list.h
> +            for (int i = 0; i <= _count; i++)
Чтобы избежать несовместимости типов, лучше вместо `int` использовать `size_type`.

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/inc/iterators.h
> +        using iterator_category = std::forward_iterator_tag;
Почему категория итератора `Forward`? Список предоставляет `Bidirectional` итераторы.

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/inc/iterators.h
> +        explicit RawIterator(const BaseNode<T> &node_ptr) : _curr_ptr(&(std::remove_const_t<BaseNode<T> &>(node_ptr))){};
Зачем нужен этот конструктор?

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/inc/iterators.h
> +            return !(*this != it);
Обычно `operator!=` реализуется через `operator==`, а не наоборот

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/inc/iterators.h
> +        bool operator>(const RawIterator<T> &it)
Обычно итераторы не предоставляют операторов сравнения на больше-меньше. К тому же реализация таких операторов не выглядит логичным "продолжением" реализаций операторов `==`, `!=`, т.к. последние не зависят от элементов, на которые "указывают" итераторы.

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/inc/iterators.h
> +        void swap(const RawIterator& it)
`swap` итераторов должен менять местами ссылки на элементы, а не значения этих элементов.

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/inc/iterators.h
> +        template <bool _isRvrs = isRvrs>
Хитро 👏, но будьте готовы ответить на вопрос о том, как это работает (раз уж используете).

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/inc/iterators.h
> +            It* result = new It(*(this->_curr_ptr));
Здесь (и в других реализациях пост-инкремента/пост-декремента) утечка памяти
1. Объясните почему;
2. Исправьте;
3. Добавьте тесты, которые будут использовать именно пост-инкременты и пост-декременты.

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/inc/iterators.h
> +            It* result = new It(*(this->_curr_ptr));
Также подумайте, можно ли реализацию пост-инкремента выразить через пре- инкремент, чтобы избежать дублирования кода. То же самое и с декрементами.

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/inc/iterators.h
> +            return dynamic_cast<It &>(*this);
Кажется, здесь (и во всех других подобных местах) можно обойтись `static_cast`, он "бесплатный"

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/inc/iterators.h
> +        It& operator=(RawIterator<T>& other)
`const` (для ссылки) потеряли?

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/inc/iterators.h
> +            It* result = new It(*(this->_curr_ptr));
Я понял вашу проблему: вы зачем то возвращаете ссылку на результат, хотя его нужно возвращать по значению (в случае пост-инкремента/пост-декремента)

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/src/linked_list.tpp
> +    for (auto item : other)
Тут следует использовать ссылку, иначе сначала произойдет копирование сначала в item, а затем из item внутрь push_back:
```cpp
for (auto& item : other)

или

for (const auto& item : other)
```

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/src/linked_list.tpp
> +LinkedList<T> &LinkedList<T>::operator=(LinkedList<T> &&other)
В текущей реализации есть утечка памяти, когда в один НЕпустой контейнер перемещается другой НЕпустой контейнер.
1. Найдите ее и объясните суть;
2. Покройте тестом этот случай.

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/inc/linked_list.h
> +            for (int i = 0; i <= count; i++)
Проверьте все остальные подобные циклы.

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/src/linked_list.tpp
> +    for (auto item : ilist)
`auto&`

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/src/linked_list.tpp
> +    for (auto item : ilist)
Подумайте, можно ли реализовать этот метод с помощью assign для избежания дублирования кода.

2021-12-15 20:53 UTC, OnePatchGuy commented on 3/src/linked_list.tpp
> +void LinkedList<T>::push_back(const T &value)
Подумайте, можно ли реализовать методы `push_<...>` с помощью других методов для избежания дублирования кода. Например, с помощью `insert`.

2021-12-15 20:53 UTC, NikitkoCent commented on 3/src/linked_list.tpp
> +    if (pos == cend())
`insert` предполагает вставку **_перед_** элементом, на который указывает итератор `pos`, поэтому вставка перед end должна быть корректной ситуацией. Фактически это добавление элемента в конец списка.

2021-12-15 20:53 UTC, NikitkoCent commented on 3/src/linked_list.tpp
> +        push_back(item);
`std::move`?

2021-12-15 20:53 UTC, NikitkoCent commented on 3/src/linked_list.tpp
> +    for (auto item : ilist)
`auto&`

2021-12-15 20:53 UTC, NikitkoCent commented on 3/src/linked_list.tpp
> +        insert(pos, item);
`std::move`?

2021-12-15 20:53 UTC, NikitkoCent commented on 3/src/linked_list.tpp
> +typename LinkedList<T>::iterator LinkedList<T>::erase(const_iterator first, const_iterator last)
Можно ли реализовать этот метод с помощью перегрузки `erase` от одного итератора?

2021-12-15 20:53 UTC, NikitkoCent commented on 3/src/linked_list.tpp
> +bool LinkedList<T>::operator==(const LinkedList<T> &l2)
Добавьте тест этого метода для случая, когда в списке слева от `==` 10 элементов, а справа - 3.

2021-12-15 20:53 UTC, NikitkoCent commented on 3/src/linked_list.tpp
> +    LinkedList<int> list = {1, 2, 3, 4, 5};
O_o

2021-12-15 20:53 UTC, NikitkoCent commented on 3/src/linked_list.tpp
> +bool LinkedList<T>::empty() const
Почему бы не навесить noexcept на этот метод?

2021-12-15 20:53 UTC, NikitkoCent commented on 3/src/linked_list.tpp
> +void LinkedList<T>::clear() noexcept
Подумайте, почему этот метод _нельзя_ помечать `noexcept`

2021-12-15 20:53 UTC, NikitkoCent commented on 3/src/linked_list.tpp
> +    for (auto item : *this)
`const auto&`

2021-12-15 20:53 UTC, NikitkoCent commented on 3/src/linked_list.tpp
> +void LinkedList<T>::print() const noexcept
Подумайте, почему этот метод _нельзя_ помечать `noexcept`

2021-12-15 20:53 UTC, NikitkoCent commented on 3/src/linked_list.tpp
> +{
Реализация некорректна, т.к. не соответствует обязательству `noexcept`. Здесь следующие проблемы, связанные с этим:
1. Создание дополнительного буфера может выбрасывать исключения. Подумайте, как можно обойтись без дополнительной памяти;
2. Перемещение объектов из одной ячейки памяти в другую в особо плохих случаях также может бросать исключения (все зависит от реализации `T`). Подумайте, как можно обойтись без перемещения элементов между ячейками памяти.

2021-12-15 20:53 UTC, NikitkoCent commented on 3/src/linked_list.tpp
> +void LinkedList<T>::sort()
Подумайте, можно ли выразить реализацию этого метода через вторую его перегрузку.

2021-12-15 20:53 UTC, NikitkoCent commented on 3/src/linked_list.tpp
> +                j.swap(i);
Сортировку можно реализовать без перемещения хранимых элементов между нодами, а лишь изменением того, какая нода на какие ссылается.

2021-12-15 20:53 UTC, NikitkoCent commented on 3/src/linked_list.tpp
> +    for (Iterator i = begin_; i != end_; ++i)
Какая алгоритмическая сложность у этого алгоритма? `std::list::sort` имеет сложность O(N * log N). Посмотрите в сторону [сортировки слиянием](https://ru.wikipedia.org/wiki/Сортировка_слиянием)

2021-12-15 20:53 UTC, NikitkoCent commented on 3/src/linked_list.tpp
> +typename LinkedList<T>::size_type LinkedList<T>::unique()
Подумайте, можно ли выразить реализацию этого метода через вторую его перегрузку.

2021-12-15 20:53 UTC, NikitkoCent commented on 3/src/linked_list.tpp
> +{
Подумайте, можно ли выразить реализацию этого метода через `remove_if`.

2021-12-15 20:53 UTC, NikitkoCent commented on 3/src/linked_list.tpp
> +        auto temp = it;
Подумайте, можно ли обойтись без `temp`

2021-12-30 16:52 UTC, Krazerleo commented on 3/.vscode/launch.json
> +{
засунул папку в .gitignore

2021-12-30 16:54 UTC, Krazerleo commented on 3/CMakeLists.txt
> +FetchContent_MakeAvailable(googletest)
поправил на 3.2.0

2021-12-30 17:00 UTC, Krazerleo commented on 3/CMakeLists.txt
> +set (CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -fno-omit-frame-pointer -fsanitize=address")
Поправил, оставил ASAN только для тестов.

2021-12-30 18:33 UTC, Krazerleo commented on 3/LinkedList_tests.cpp
> +    LinkedList<int> list1 = std::move(list);
Я исправил, и у меня появилась утечка на 48kb. Я пытался это исправить, но у меня не получилось.

2021-12-30 18:55 UTC, Krazerleo commented on 3/LinkedList_tests.cpp
> +    LinkedList<int> list1 = std::move(list);
Теперь без утечки. Я забыл то, что прежде чем присваивать что то указателю, перед этим надо удалить то, на что он указывает.

2021-12-30 21:11 UTC, Krazerleo commented on 3/inc/linked_list.h
> +        LinkedList() : count(0), head(new BaseNode<T>()), tail(new BaseNode<T>())
1) Из методов там только конструкторы, а если их перенести в tpp файл то компилятор ругается на то что я их переопределяю. А если все перенести в один хеддер то это тоже не круто.
2)На все имплиментации linked list где я смотрел head и tail хранятся в виде указателей. В моем коде они зачастую nullptr.

2021-12-30 21:15 UTC, Krazerleo commented on 3/inc/linked_list.h
> +        void push_front();
Заприватил.

2021-12-30 21:28 UTC, Krazerleo commented on 3/inc/linked_list.h
> +            for (; first != last; first++)
Поправил. В цикле не имеет смысла использовать пост-инкремент, тк он создает свою прошлую копию, которую мы не используем.

2021-12-30 21:33 UTC, Krazerleo commented on 3/inc/linked_list.h
> +        void push_back();
Заприватил

2021-12-30 21:40 UTC, Krazerleo commented on 3/inc/iterators.h
> +        explicit RawIterator(const BaseNode<T> &node_ptr) : _curr_ptr(&(std::remove_const_t<BaseNode<T> &>(node_ptr))){};
Что бы принимать ссылки на константные ноды. Если вы помните, то я когда пытался сдать эту лабу, мы решили убрать его и все сломалось. Боюсь он уже на всю жизнь с нами(...

2021-12-30 22:46 UTC, Krazerleo commented on 3/src/linked_list.tpp
> +void LinkedList<T>::clear() noexcept
Во время стирания нод могут возникнуть ошибки при удалении я так думаю, поэтому и не стоит его так помечать.

2021-12-30 22:54 UTC, Krazerleo commented on 3/src/linked_list.tpp
> +void LinkedList<T>::print() const noexcept
Если встретим пустые указатели нам будет плохо.

2021-12-30 23:03 UTC, Krazerleo commented on 3/src/linked_list.tpp
> +        auto temp = it;
Если бы erase возращал константный итератор, то можно и без temp обойтись бы было.

2022-01-01 15:49 UTC, Krazerleo commented on 3/inc/iterators.h
> +            It* result = new It(*(this->_curr_ptr));
При использование пост инкремента у меня создавался в дин. памяти объект, ссылка на который может пропасть если не присвоить результат, из-за чего возникает утечка памяти. Если возращать по значению, то оно будет на стеке и удалится в конце скоупа сама.

2022-01-01 16:03 UTC, Krazerleo commented on 3/src/linked_list.tpp
> +LinkedList<T> &LinkedList<T>::operator=(LinkedList<T> &&other)
Возможно я что-то поменял в коде, но у меня утечки никакой нет. Тест подтвердит.

2022-01-01 19:01 UTC, Krazerleo commented on 3/src/linked_list.tpp
> +                j.swap(i);
Про это вроде был один из предыдущих комментариев, который я поправил(надеюсь).

2022-01-01 19:22 UTC, Krazerleo commented on 3/src/linked_list.tpp
> +        auto temp = it;
Но я поправил, теперь без temp.

2022-01-01 19:23 UTC, Krazerleo commented on 3/src/linked_list.tpp
> +                j.swap(i);
Это ссылается к прошлому комментарию, который я надеюсь поправил.

2022-01-03 07:39 UTC, NikitkoCent requested changes
13 замечаний/вопросов

2022-01-03 07:39 UTC, OnePatchGuy commented on 3/CMakeLists.txt
> +set (CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -fno-omit-frame-pointer -fsanitize=address")
Кажется, все еще не поправил

2022-01-03 07:39 UTC, OnePatchGuy commented on 3/CMakeLists.txt
> +FetchContent_MakeAvailable(googletest)
Кажется, все еще не поправил

2022-01-03 07:39 UTC, OnePatchGuy commented on 3/CMakeLists.txt
> +FetchContent_MakeAvailable(googletest)
А почему 3.2.0? 3.14.7 сильно новее 3.2.0, а 3.2.0 все еще не сможет собрать такой CMakeLists, т.к. `FetchContent_MakeAvailable` появился только в 3.14

2022-01-03 07:39 UTC, OnePatchGuy commented on 3/CMakeLists.txt
> +if (NOT MSVC)
А почему вариант для MSVC не предусмотрен? Насколько я знаю, для него также все должно работать, только нужно передавать ровно один флаг `/fsanitize=address`

2022-01-03 07:39 UTC, OnePatchGuy commented on 3/CMakeLists.txt
> +target_compile_options(${PROJECT_NAME} PUBLIC $<$<COMPILE_LANGUAGE:CXX>:-std=c++17>)
Правильные способы включения нужного стандарта в порядке от наиболее предпочтительного к наименее предпочтительному:
1. [Requiring Language Standards](https://cmake.org/cmake/help/latest/manual/cmake-compile-features.7.html#requiring-language-standards) - современный способ включения нужного стандарта;
2. Через проперти таргетов `CXX_STANDARD`, `CXX_REQUIRED` примерно так:
```cmake
set_target_properties(target_name PROPERTIES
    CXX_STANDARD 17
    CXX_REQUIRED ON
    CXX_EXTENSIONS OFF
)
```
3. Через глобальные проперти `CMAKE_CXX_STANDARD`, `CMAKE_CXX_REQUIRED` ; пример - https://github.com/NikitkoCent/cpp-xor-list/blob/24bd6b8a0fcdd697cdf0d9e0ccfbdc076bb4b047/CMakeLists.txt#L4) - модифицируют "глобальное" состояние, тем самым влияя на все таргеты, что обычно нежелательно.


Полагаю, твой текущий способ включения ломает сборку на [macOS](https://github.com/NikitkoCent/engnr-nsu-cpp-2021/runs/4688219882?check_suite_focus=true#step:4:49) и [Windows](https://github.com/NikitkoCent/engnr-nsu-cpp-2021/runs/4688219882?check_suite_focus=true#step:4:49).

2022-01-03 07:39 UTC, OnePatchGuy commented on 3/LinkedList_tests.cpp
> +//Такой милый кейс, но clang с msvc на тестере подавились им(
Попробуйте к этапу устной сдачи найти ответ (или осознать), почему такого рода тесты "не работают".

2022-01-03 07:39 UTC, OnePatchGuy commented on 3/src/linked_list.tpp
> +typename LinkedList<T>::iterator LinkedList<T>::erase(const_iterator first, const_iterator last)
P.S. хм, я ожидал что-то вроде
```cpp
for (; first != last; ) {
    first = erase(first);
}
```

2022-01-03 07:39 UTC, OnePatchGuy commented on 3/inc/linked_list.h
> +        LinkedList() : count(0), head(new BaseNode<T>()), tail(new BaseNode<T>())
>а если их перенести в tpp файл то компилятор ругается на то что я их переопределяю

Значит что-то не так делаете, может забыли удалить определение из .h, когда скопировали его в .tpp?

2022-01-03 07:39 UTC, OnePatchGuy commented on 3/inc/linked_list.h
> +            for (int i = 0; i <= count; i++)
Все еще не исправлено.

2022-01-03 07:39 UTC, NikitkoCent commented on 3/inc/iterators.h
> +        void swap(const RawIterator& it)
Все еще не исправлено. Кстати, а почему `it` принимается по константной ссылке? В таком случае поменять местами содержимое `this` и `it` не выйдет :(

2022-01-03 07:39 UTC, NikitkoCent commented on 3/src/linked_list.tpp
> +LinkedList<T> &LinkedList<T>::operator=(LinkedList<T> &&other)
Ага, теперь все ок.

2022-01-03 07:39 UTC, NikitkoCent commented on 3/src/linked_list.tpp
> +bool LinkedList<T>::operator==(const LinkedList<T> &l2)
Тест-то добавили?)

2022-01-03 07:39 UTC, NikitkoCent commented on 3/src/linked_list.tpp
> +{
`value` в данном случае лучше захватить по ссылке, чтобы избежать копирования внутрь лямбды:
```cpp
[&value](auto& item) .....
```

2022-01-03 12:31 UTC, Krazerleo commented on 3/CMakeLists.txt
> +FetchContent_MakeAvailable(googletest)
Я почему то решил что порядок версий лексикографический хехе.

2022-01-03 12:34 UTC, Krazerleo commented on 3/CMakeLists.txt
> +FetchContent_MakeAvailable(googletest)
Я почему-то решил что порядок лексикографический ).

2022-01-03 12:35 UTC, Krazerleo commented on 3/src/linked_list.tpp
> +bool LinkedList<T>::operator==(const LinkedList<T> &l2)
Да, Equality_Test_Simple название теста.

2022-01-03 13:12 UTC, Krazerleo commented on 3/inc/linked_list.h
> +        LinkedList() : count(0), head(new BaseNode<T>()), tail(new BaseNode<T>())
Ну я разобрался, оказывается из-за init листа у меня и возникало переопределение. Это было очень неочевидно.

2022-01-03 13:25 UTC, Krazerleo commented on 3/LinkedList_tests.cpp
> +//Такой милый кейс, но clang с msvc на тестере подавились им(
Почему не работают, работают, только на g++ правда.

2022-01-03 14:08 UTC, Krazerleo commented on 3/inc/iterators.h
> +        void swap(const RawIterator& it)
Мне кажется я не смогу свапать их адресса, тк у меня data хранится по значению в ноде.

2022-01-03 23:46 UTC, NikitkoCent commented on 3/CMakeLists.txt
> +if (NOT MSVC)
Для линковщика тоже.

2022-01-03 23:57 UTC, NikitkoCent commented on 3/inc/iterators.h
> +        void swap(const RawIterator& it)
У вас итератор фактически является указателем на ноду + всякие дополнительные операции. Раз итератор - указатель на ноду, то почему своп итераторов свопает значения в нодах, а не указатели на эти самые ноды?

2022-01-04 00:02 UTC, NikitkoCent requested changes
1. Пара замечаний;
2. CI прогоны Windows и macOS красные.

Решение готово к этапу устной сдачи, но без правок по пунктам выше зачтено не будет независимо от результата устной сдачи.

2022-01-05 01:02 UTC, NikitkoCent approved these changes
Замечаний по коду больше нет; этап устной сдачи также успешно пройден.

Лабораторная засчитана; полный балл.

2022-01-05 01:06 UTC, closed without merging