vveselov-lab1
NikitkoCent/engnr-nsu-cpp-2021 pull request #15
Opened 2021-11-26 14:52 UTC by vlad00k

2021-12-03 03:39 UTC, NikitkoCent requested changes
9 замечаний/вопросов

2021-12-03 03:39 UTC, OnePatchGuy commented on 1/README.md
> +Утилита может считать 2 варианта хеша:
Нет инструкций по сборке программы

2021-12-03 03:39 UTC, OnePatchGuy commented on cmake-build-debug/CMakeFiles/3.20.2/CMakeCCompiler.cmake
> +set(CMAKE_C_COMPILER "C:/Program Files (x86)/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/bin/gcc.exe")
Директория `cmake-build-debug` содержит артефакты сборки. Их не следует добавлять в репозиторий. Нужно удалить.

2021-12-03 03:39 UTC, OnePatchGuy commented on README.md
> -# engnr-nsu-cpp-2021
Зачем файл удален?

2021-12-03 03:39 UTC, OnePatchGuy commented on 1/hash.hpp
> +ArgHelper* getArg(int argc, char* argv[]) {
Пожалуйста, разделите объявления и реализации функций/методов по `.h` и `.cpp` файлам

2021-12-03 03:39 UTC, OnePatchGuy commented on 1/hash.hpp
> +    ArgHelper* argHelper = new ArgHelper();
1. Эта строчка провоцирует утечку памяти. Объясните почему.
2. Зачем этот объект создавать в динамической памяти?

2021-12-03 03:39 UTC, NikitkoCent commented on 1/main.cpp
> +            callAdler32(arg->path); cout << endl;
С каким кодом ошибки завершится программа, если внутри `callAdler32` произойдет ошибка?

2021-12-03 03:39 UTC, NikitkoCent commented on 1/hash.hpp
> +int callAdler32(string fileName) {
Рассмотрим такой код:
```cpp
std::string myString = "Some string";
callAdler32(myString);
```

Как связано содержимое `myString` и содержимое параметра функции (`fileName`)? Есть ли в данном случае способ сделать передачу параметров в функцию более эффективной?

2021-12-03 03:39 UTC, NikitkoCent commented on 1/hash.hpp
> +int callSumm64(string fileName) {
Функции `callAdler32`, `callSumm64` по своему содержимому очень похожи. Подумайте, как можно их объединить в одну функцию, чтобы избежать процент дублирования кода.

2021-12-03 03:39 UTC, NikitkoCent commented on 1/hash.hpp
> +using namespace std;
Это считается дурным тоном.
Подробнее: https://habr.com/ru/post/580204/

2021-12-03 06:33 UTC, NikitkoCent requested changes
+1 замечание

2021-12-03 06:33 UTC, NikitkoCent commented on 1/hash.hpp
> +void show_err() {
Содержимое функции `show_help` и `show_err` с 3ей строки практически идентично. Подумайте, как можно их объединить в одну функцию, чтобы избежать процент дублирования кода (подсказка: воспользуйтесь `std::ostream&`)

2021-12-13 16:35 UTC, NikitkoCent requested changes
6 замечаний

2021-12-13 16:35 UTC, NikitkoCent commented on 1/README.md
> +Утилита может считать 2 варианта хеша:
Все еще не исправлено

2021-12-13 16:35 UTC, NikitkoCent commented on README.md
> -# engnr-nsu-cpp-2021
Все еще не исправлено

2021-12-13 16:35 UTC, NikitkoCent commented on 1/hash.hpp
> +#include <iostream>
В продолжение https://github.com/NikitkoCent/engnr-nsu-cpp-2021/pull/15#discussion_r761613992:

Такое разделение не является "правильным":
1. Все объявления (но не определения) должны находиться в `.h` (или `.hpp`);
2. Все определения, объявленные в `.h`/`.hpp`, должны находиться в `.cpp`
3. Все, кому нужна обсуждаемая функциональность, подключают ее заголовочный `.h`/`.hpp` файл (а не `.cpp`)

2021-12-13 16:35 UTC, NikitkoCent commented on 1/hash.cpp
> +ArgHelper getArg(int argc, char* argv[]) {
Раньше эта функция имела вид `ArgHelper* getArg(...`, а результат создавался следующим кодом:
```cpp
ArgHelper* argHelper = new ArgHelper();
```

Вы избавились от использования динамической памяти, но не ответили на вопрос (https://github.com/NikitkoCent/engnr-nsu-cpp-2021/pull/15#discussion_r761614939):
>Эта строчка провоцирует утечку памяти. Объясните почему.

2021-12-13 16:35 UTC, NikitkoCent commented on 1/main.cpp
> +                uint32_t r = (uint32_t)result;
С каким кодом ошибки завершится эта программа, если она попадет в этот `if`?

2021-12-13 16:35 UTC, NikitkoCent commented on 1/main.cpp
> +                std::cout << std::hex << result;
С каким кодом ошибки завершится эта программа, если она попадет в этот `if`?

2021-12-13 16:35 UTC, NikitkoCent commented on 1/main.cpp
> +    if (arg.isMode()) {
С каким кодом ошибки завершится эта программа, если она _не_ попадет в этот `if`?

2021-12-15 18:35 UTC, vlad00k commented on 1/hash.cpp
> +ArgHelper getArg(int argc, char* argv[]) {
Потому что я ее не удалял :)

2021-12-15 18:35 UTC, vlad00k commented on 1/README.md
> +Утилита может считать 2 варианта хеша:
не получается собрать :(  
выдает 
CMake Error at CMakeLists.txt:2 (project):
  Running

   'nmake' '-?'

  failed with:

   Не удается найти указанный файл

2021-12-15 18:35 UTC, vlad00k commented on 1/hash.cpp
> +ArgHelper getArg(int argc, char* argv[]) {
Я не удалял созданный объект при  помощи new,   но еще проблема с самим delete:
Можно вообще забыть вызвать delete (утечка памяти, memory leak).
Можно забыть вызвать delete в случае исключения или досрочного возврата из функции (тоже утечка памяти).
Можно вызвать delete дважды (двойное удаление, double delete).
Можно вызвать не ту форму оператора: delete вместо delete[] или наоборот (неопределённое поведение, undefined behavior).
Можно использовать объект после вызова delete (dangling pointer).
Поэтому лучше избегать......

2021-12-18 06:27 UTC, closed without merging