Mshpital lab2
NikitkoCent/engnr-nsu-cpp-2021 pull request #18
Opened 2021-12-03 10:34 UTC by maksimshpital

2021-12-13 17:54 UTC, NikitkoCent requested changes
9 замечаний.

2021-12-13 17:54 UTC, OnePatchGuy commented on 2/AppException.h
> +    AppException(std::string& err){
Пожалуйста, разделите объявления и реализации (определения) классов/методов/функций на заголовочные (`.h`) и `.cpp` файлы

2021-12-13 17:54 UTC, NikitkoCent commented on 2/tests/unit_tests.cpp
> +TEST(TestCommands, test_pop_command) {
Как собрать и запустить эти тесты?

2021-12-13 17:54 UTC, NikitkoCent commented on 2/README.md
> +``cd tests``
Это не работает

2021-12-13 17:54 UTC, NikitkoCent commented on 2/README.md
> +``cd tests``
Пожалуйста, посмотрите как интегрировать GoogleTest с CMake и с CTest

2021-12-13 17:54 UTC, NikitkoCent commented on 2/README.md
> +# Cpp-Lab2
Тесты (мои) не проходят.

2021-12-13 17:54 UTC, NikitkoCent commented on 2/Context.h
> +    std::stack<int> stack;
1. В методических указаниях к лабораторной есть требование использовать 64-битные знаковые целые числа (`std::int64_t`), тогда как у вас используется `int`;
2. Если вы собираетесь сдавать также вторую часть лабы (которая про использование `SafeInt`), то вам нужно ее задействовать всюду для хранения чисел.

2021-12-13 17:54 UTC, NikitkoCent commented on 2/Context.cpp
> +#include "Context.h"
Зачем нужен этот файл?

2021-12-13 17:54 UTC, NikitkoCent commented on 2/CommandCreator.cpp
> +        creatorNoArg.create(tokens.at(0))->execute(ctx);
Эта строчка и все другие вида `.create(...)->execute(...);` вызывают утечку памяти.

1. Объясните почему.
2. Могут ли тут помочь умные указатели?

2021-12-13 17:54 UTC, NikitkoCent commented on 2/Command.h
> +class Command {
Что такое виртуальный деструктор? Нужно ли для классов команд его использовать? Почему?

2021-12-14 04:14 UTC, maksimshpital commented on 2/Command.h
> +class Command {
виртуальный деструктор нужен, чтобы в наследованном классе, который у нас есть (от базового) можно было вызвать (прямо оттуда) деструктор базового, а т.к. простой деструктор наследованный класс не понимает, то нужно создавать виртуальный.
И все это чтобы не было никакой утечки памяти

2021-12-14 04:22 UTC, maksimshpital commented on 2/CommandCreator.cpp
> +        creatorNoArg.create(tokens.at(0))->execute(ctx);
Потому что у меня есть унаследованный класс , внутри которого есть выделение памяти. Для него нужен виртуальный деструктор, где я эту память освобожу. Виртуальный деструктор нужен, чтобы он вызвался. А если у меня например в конструкторе классе есть выделение памяти, то в деструкторе будет освобождение.
И если деструктор не вызвался - память не освободилась и утекла. Да, умные указатели помочь могут

2021-12-14 10:07 UTC, NikitkoCent commented on 2/CommandCreator.cpp
> +        creatorNoArg.create(tokens.at(0))->execute(ctx);
1. Хм, виртуальный деструктор, конечно, нужен, но у нас для него отдельная дискуссия. В обсуждаемом коде есть еще одна проблема, вызывающая утечку памяти.
2. Умные указатели как раз и помогут решить эту "еще одну" проблему. Объясните как именно (и исправьте)

2021-12-14 10:09 UTC, NikitkoCent commented on 2/Command.h
> +class Command {
Ответ верный, осталось ему последовать :)

2021-12-27 12:17 UTC, maksimshpital commented on 2/Context.cpp
> +#include "Context.h"
Удалил. Файл был ненужен, т.к был пустой

2021-12-27 21:38 UTC, NikitkoCent commented on 2/README.md
> +``cd tests``
Тесты все еще не интегрированы с CTest

2021-12-27 22:03 UTC, NikitkoCent requested changes
2 замечания/вопроса.

2021-12-27 22:03 UTC, OnePatchGuy commented on 2/CommandCreator.cpp
> +        creatorNoArg.create(tokens.at(0))->execute(ctx);
Исправили, но не объяснили.

2021-12-27 22:03 UTC, NikitkoCent commented on 2/tests/unit_tests.cpp
> +TEST(TestCommands, test_pop_command) {
Тесты все еще не интегрированы с CTest.

2022-01-07 07:00 UTC, maksimshpital commented on 2/CommandCreator.cpp
> +        creatorNoArg.create(tokens.at(0))->execute(ctx);
Так, что в случае если у меня возникнет исключение и прога свалиться они почистят память, а так же раньше было new, и нам надо было хранить сырые указатели, чтобы потом для них delete вызвать, у меня этого  не было.

2022-01-07 13:01 UTC, maksimshpital commented on 2/tests/unit_tests.cpp
> +TEST(TestCommands, test_pop_command) {
Давай сойдемся на том, что я писал в телеге  :))))

2022-01-08 08:59 UTC, NikitkoCent approved these changes
Первые две части лабораторной готовы к устной сдаче.

2022-01-09 23:11 UTC, NikitkoCent commented
Лабораторная принята (без этапа устной сдачи).

2022-01-09 23:11 UTC, closed without merging