Dtaranets lab2
NikitkoCent/engnr-nsu-cpp-2021 pull request #20
Opened 2021-12-10 11:02 UTC by dan-taranetc

2021-12-14 10:19 UTC, NikitkoCent commented
Тесты (мои) не проходят.

2021-12-14 22:16 UTC, NikitkoCent requested changes
10 замечаний + на Windows тесты (мои) не проходят.

2021-12-14 22:16 UTC, OnePatchGuy commented on .gitmodules
> +[submodule "2/SafeInt"]
Зачем 2 самбодуля `SafeInt`?

2021-12-14 22:16 UTC, OnePatchGuy commented on 2/build/.gitignore
> -*
Зачем удален этот файл?

2021-12-14 22:16 UTC, OnePatchGuy commented on 2/build/README.md
> -# build directory
Зачем удален этот файл?

2021-12-14 22:16 UTC, OnePatchGuy commented on 2/tests/CMakeLists.txt
> +add_executable(calculator_tests
Эту штуку нужно интегрировать с CTest, иначе ваши юнит-тесты на GitHub не будут запускаться. Посмотрите на функцию `add_test()`

2021-12-14 22:16 UTC, OnePatchGuy commented on 2/src/commands/StackCalc.h
> +    virtual void command(std::stack<SafeInt<int64_t, CustomException>> &stack, std::map<std::string, SafeInt<int64_t, CustomException>> &variables) = 0;
Несоблюден пункт из методических указаний к лабораторной:
>Содержимое стека и список (лучше ассоциативный контейнер) определенных именованных параметров передавать команде в виде специального объекта — контекста исполнения;

2021-12-14 22:16 UTC, OnePatchGuy commented on 2/src/commands/StackCalc.cpp
> +        throw;
Какой объект исключения выбрасывается в этом случае и где он отлавливается?

2021-12-14 22:16 UTC, OnePatchGuy commented on 2/src/commands/StackCalc.cpp
> +        throw;
Обратите внимание на пункт в методических указаниях:
>Разработать иерархию исключений, которые _**команды будут выбрасывать при исполнении**_. В случае возникновения исключения — выводить информацию об ошибке в стандартный поток вывода ошибок (std::cerr) и завершать выполнение программы с ненулевым кодом ошибки.

2021-12-14 22:16 UTC, OnePatchGuy commented on 2/src/commands/StackCalc.cpp
> +        stack.push(abs((int64_t)val));
Стандартная реализация abs не обрабатывает ошибки целочисленного переполнения.
1. Нужно либо найти в SafeInt реализацию abs, либо реализовать ее самостоятельно.
2. Добавьте тест, который будет проверять, что команда `ABS` при переполнении выбросит исключение.

2021-12-14 22:16 UTC, NikitkoCent commented on 2/src/commands/StackCalc.cpp
> +            delete cmd;
1. Что такое умные указатели? Помогут ли они в этой задаче упростить код? Почему?
2. Примените их.

2021-12-14 22:16 UTC, NikitkoCent commented on 2/tests/CMakeLists.txt
> +add_executable(calculator_tests
Если все сделаете правильно, в логах:
1. [Windows](https://github.com/NikitkoCent/engnr-nsu-cpp-2021/runs/4526787511?check_suite_focus=true#step:5:23);
2. [Linux](https://github.com/NikitkoCent/engnr-nsu-cpp-2021/runs/4526787418?check_suite_focus=true#step:5:17);
3. [macOS](https://github.com/NikitkoCent/engnr-nsu-cpp-2021/runs/4526787459?check_suite_focus=true#step:6:17).

Вместо строчки `No tests were found` будет статус прогона ваших тестов.

2021-12-17 09:12 UTC, dan-taranetc commented
Все поправил, только unit тесты не работают из-за проблемы с путями к файлам.

2021-12-18 15:24 UTC, dan-taranetc commented
Теперь точно все поправил)

2021-12-18 16:52 UTC, NikitkoCent commented
> (кроме unit тестов)

Жду исправления

2021-12-18 17:55 UTC, dan-taranetc commented
Все поправил

2021-12-18 23:06 UTC, NikitkoCent requested changes
12 вопросов/замечаний

2021-12-18 23:06 UTC, OnePatchGuy commented on 2/build/.gitignore
> -*
Все еще не исправлено.

2021-12-18 23:06 UTC, OnePatchGuy commented on 2/build/README.md
> -# build directory
Все еще не исправлено.

2021-12-18 23:06 UTC, OnePatchGuy commented on 2/src/commands/StackCalc.h
> +typedef struct context_execution {
В C++ можно писать просто `struct ContentExecution`

2021-12-18 23:06 UTC, OnePatchGuy commented on 2/src/commands/StackCalc.cpp
> +        SafeInt<int64_t> val = std::stoi(params);
std::stoi возвращает `int`, который обычно != `int64_t`. Посмотрите в сторону `std::from_chars`

2021-12-18 23:06 UTC, OnePatchGuy commented on 2/src/commands/StackCalc.cpp
> +        context_execution.stack.push((int64_t) val1 + (int64_t) val2);
Напишите на эту команду тест, который будет ожидать выбрасывание исключения при переполнении `int64_t`.

2021-12-18 23:06 UTC, OnePatchGuy commented on 2/src/commands/StackCalc.cpp
> +        context_execution.stack.push((int64_t) val1 + (int64_t) val2);
Вот чему равен максимум `int64_t`: https://godbolt.org/z/EGfx9fx9G

2021-12-18 23:06 UTC, OnePatchGuy commented on 2/src/commands/StackCalc.cpp
> +            context_execution.stack.push(-(int64_t) val);
Напишите на эту команду тест, который будет ожидать выбрасывания исключения при переполнении `int64_t`. Для этого нужно применить ABS на минимальном значении `int64_t`.

2021-12-18 23:06 UTC, OnePatchGuy commented on 2/src/commands/StackCalc.cpp
> +        context_execution.stack.push(std::stoi(val));
`std::stoi` возвращает `int`, который обычно != `int64_t`. Посмотрите в сторону `std::from_chars`

2021-12-18 23:06 UTC, NikitkoCent commented on 2/src/commands/StackCalc.cpp
> +            throw;
Какой объект исключения выбрасывается в таком случае?

2021-12-18 23:06 UTC, NikitkoCent commented on 2/src/commands/StackCalc.cpp
> +            throw;
Напишите тест, который будет ожидать выбрасывание исключения при неизвестной команде.

2021-12-18 23:06 UTC, NikitkoCent commented on 2/src/commands/StackCalc.cpp
> +            std::unique_ptr<Command> cmd(calculator.read_command(command_line));
Как примерно работает `std::unique_ptr`?

2021-12-18 23:06 UTC, NikitkoCent commented on 2/src/commands/StackCalc.cpp
> +        context_execution.stack.push((int64_t) val2 / (int64_t) val1);
Напишите тест, который при делении на 0 будет ожидать выбрасывания исключения.

2021-12-19 07:50 UTC, dan-taranetc commented on 2/src/commands/StackCalc.cpp
> +            std::unique_ptr<Command> cmd(calculator.read_command(command_line));
Умный указатель нужен здесь для удаления объекта, когда указатель выходит из зоны видимости, также его нельзя копировать, можно только переместить.

2021-12-19 07:50 UTC, dan-taranetc commented
Все исправил

2021-12-21 15:33 UTC, NikitkoCent requested changes
2 замечания/вопроса. Если успеете исправить, можете приходить на этап устной сдачи.

2021-12-21 15:33 UTC, NikitkoCent commented on 2/tests/tests_all.cpp
> +        EXPECT_EQ(e.what(), result);
Такой тест будет успешно пройден даже в случае, если исключение не будет выброшено вовсе. Воспользуйтесь `EXPECT_THROW`

2021-12-21 15:33 UTC, NikitkoCent commented on 2/tests/tests_all.cpp
> +        EXPECT_EQ(e.what(), result);
Не забудьте поправить все аналогичные тесты.

2021-12-21 16:31 UTC, NikitkoCent submitted a review, later dismissed

2021-12-22 13:34 UTC, NikitkoCent approved these changes

2021-12-22 13:35 UTC, NikitkoCent commented
Лабораторная сдана; полный балл.

2021-12-22 13:35 UTC, closed without merging