M.Okan lab2
NikitkoCent/engnr-nsu-cpp-2021 pull request #23
Opened 2021-12-15 10:13 UTC by okm-lab

2021-12-15 22:45 UTC, NikitkoCent requested changes
12 замечаний/вопросов

2021-12-15 22:45 UTC, OnePatchGuy commented on 2/stack_calc.cbp
> +<?xml version="1.0" encoding="UTF-8"?>
Этот файл не относится к исходным файлам решения лабораторной. Его в PR быть не должно.

2021-12-15 22:45 UTC, OnePatchGuy commented on 2/README.md
> +# Stack calc lab.
Нет инструкций по сборке.

2021-12-15 22:45 UTC, OnePatchGuy commented on 2/StackCalc.h
> +        SafeInt<long> last;
Зачем это поле?

2021-12-15 22:45 UTC, OnePatchGuy commented on 2/Actions.h
> +    typedef struct context {
В C++ можно писать просто `struct Context`

2021-12-15 22:45 UTC, OnePatchGuy commented on 2/main.cpp
> +    catch (SafeIntException &err) {
Если параметр (`err`) не используется, его имя можно просто не указывать:
```cpp
catch (SafeIntException &)
```

2021-12-15 22:45 UTC, NikitkoCent commented on 2/CMakeLists.txt
> +add_executable(stack_calc_test)
Нужно интегрировать ваш исполняемый файл с тестами с CTest. Поищите как это сделать; вам понадобятся функции CMake `enable_testing()` и `add_test()`.

Если все сделаете правильно, то в логах CI:
1. [Windows](https://github.com/NikitkoCent/engnr-nsu-cpp-2021/runs/4533266305?check_suite_focus=true#step:5:23);
2. [Linux](https://github.com/NikitkoCent/engnr-nsu-cpp-2021/runs/4533266180?check_suite_focus=true#step:5:17);
3. [macOS](https://github.com/NikitkoCent/engnr-nsu-cpp-2021/runs/4533266239?check_suite_focus=true#step:6:17).

Вместо строчек `No tests were found!!!`/`No test configuration file found!` будут логи прогона ваших тестов.

2021-12-15 22:45 UTC, NikitkoCent commented on 2/Actions.h
> +        std::stack<SafeInt<long>> st;
Методические указания к лабораторной содержат требование о том, что калькулятор должен оперировать 64-битными знаковыми целыми числами. `long` же совсем не гарантировано является 64-битным.

Воспользуйтесь псевдонимами целочисленных типов из заголовочного файла `<cstdint>`.

(не забудьте исправить и в других местах кода)

2021-12-15 22:45 UTC, NikitkoCent commented on 2/SpecificActionCreator.cpp
> +std::map<std::string, std::function<StackActions::Action*(std::string)>> actions = {
1. Почему бы не сделать этот объект (`actions`) полем (статическим) класса `SpecificActionCreator`, ведь он является частью реализации этого класса.
2. Предлагаю переделать функции так, чтобы они сразу возвращали объекты умных указателей на команду (вместо голых `StackActions::Action*`). Есть ли у этого преимущества?

2021-12-15 22:45 UTC, NikitkoCent commented on 2/SpecificActionCreator.cpp
> +    if ((action[0] != '#') && (action.length())) {
Как отработает этот if, если длина `action` = 0?

2021-12-15 22:45 UTC, NikitkoCent commented on 2/SpecificActionCreator.cpp
> +    if ((action[0] != '#') && (action.length())) {
Напишите тест на такой случай

2021-12-15 22:45 UTC, NikitkoCent commented on 2/Actions.cpp
> +    return !s.empty() && std::all_of(s.begin(), s.end(), [](char c) {return ::isdigit(c) || c == '-';});
Что будет, если `s` == `123-456`?
Напишите тест на такой случай.

2021-12-15 22:45 UTC, NikitkoCent commented on 2/Actions.cpp
> +    context.st.push(std::stol(value));
`std::stol` преобразует строку в `long`, что совсем необязательно == 64-битный int. Попробуйте воспользоваться [std::from_chars](https://en.cppreference.com/w/cpp/utility/from_chars)

2021-12-16 04:09 UTC, okm-lab commented on 2/SpecificActionCreator.cpp
> +    if ((action[0] != '#') && (action.length())) {
Это любой тест с пустыми строками, изначально я считал их ошибками и выбрасывал исключения, но судя по тестам это нормальная ситуация, и как раз для этого я добавил дополнительное условие на длину

2021-12-16 04:46 UTC, okm-lab commented on 2/CMakeLists.txt
> +add_executable(stack_calc_test)
А если так?

enable_testing()
include(GoogleTest)
gtest_discover_tests(stack_calc_test)

2021-12-16 05:03 UTC, okm-lab commented on 2/SpecificActionCreator.cpp
> +std::map<std::string, std::function<StackActions::Action*(std::string)>> actions = {
2. Это уже навредит читаемости кода, строки будут слишком длинными и смысл использовать лямбда функции совсем пропадёт

2021-12-18 15:12 UTC, NikitkoCent commented on 2/SpecificActionCreator.cpp
> +    if ((action[0] != '#') && (action.length())) {
Вы не поняли сути вопроса. Распишите, что будет проверять этот if и в какой последовательности.

2021-12-18 15:36 UTC, NikitkoCent requested changes
3 замечания/вопроса

2021-12-18 15:36 UTC, NikitkoCent commented on 2/test.cpp
> +        calc.execute(in);
Такой тест засчитается пройденным, даже в случае, если исключение не будет выброшено вовсе. Посмотрите в сторону `EXPECT_THROW`

2021-12-18 15:36 UTC, NikitkoCent commented on 2/test.cpp
> +        calc.execute(in);
Исправьте все аналогичные случаи в ваших тестах.

2021-12-18 15:36 UTC, NikitkoCent commented on 2/SpecificActionCreator.cpp
> +    if (actions.count(action) == 0) {
Сколько раз в этом методе производится поиск внутри `actions`? Можно ли сократить это количество до 1?

2021-12-18 17:09 UTC, okm-lab commented on 2/SpecificActionCreator.cpp
> +    if ((action[0] != '#') && (action.length())) {
Понял... Но это работало, все тесты проходило

2021-12-20 04:21 UTC, okm-lab commented on 2/SpecificActionCreator.cpp
> +    if (actions.count(action) == 0) {
1, сейчас я заменил на try-except, поэтому уже 0

2021-12-21 10:13 UTC, NikitkoCent commented on 2/SpecificActionCreator.cpp
> +    if (actions.count(action) == 0) {
Еще можно было бы воспользоваться методом `find` (вместо `at`)

2021-12-21 10:21 UTC, NikitkoCent requested changes
1 замечание/вопрос. Если успеете исправить, жду на этап устной сдачи.

2021-12-21 10:21 UTC, NikitkoCent commented on 2/Actions.cpp
> +    context.st.push(std::stol(value));
Все еще не исправлено

2021-12-21 14:43 UTC, NikitkoCent approved these changes
По коду больше замечаний/вопросов нет.

2021-12-22 13:30 UTC, NikitkoCent commented
Лабораторная сдана; полный балл.

2021-12-22 13:30 UTC, closed without merging