Tuskova lab1
NikitkoCent/engnr-nsu-cpp-2021 pull request #24
Opened 2021-12-17 06:14 UTC by Tatame

2021-12-18 15:38 UTC, NikitkoCent requested changes
2 замечания/вопроса

2021-12-18 15:38 UTC, NikitkoCent commented on 1/main.cpp
> +    if(file.peek() == EOF){
Можно ли обойтись без этого?

2021-12-18 15:38 UTC, NikitkoCent commented on 1/main.cpp
> +    file.open(path, std::ios_base::binary);
Зачем нужен `std::ios_base::binary`?

2021-12-21 15:15 UTC, Tatame commented on 1/main.cpp
> +    file.open(path, std::ios_base::binary);
Чтобы все считывалось по байтам независимо от типа данных, например, чтобы картинки считывались тоже просто как последовательность байт.

2021-12-21 15:19 UTC, Tatame commented on 1/main.cpp
> +    if(file.peek() == EOF){
Да, теперь работает и без этого

2021-12-21 16:18 UTC, NikitkoCent approved these changes
По коду замечаний/вопросов больше нет.

По 

На этапе устной сдачи будьте готовы:
1. Рассказать, как работает решение в целом;
2. Продемонстрировать сборку вашего приложения с нуля с помощью cmake из консоли;
3. Продемонстрировать работу программы.

2021-12-23 11:25 UTC, NikitkoCent commented
Лабораторная сдана; полный балл.

2021-12-23 11:25 UTC, closed without merging