Alinke lab1
NikitkoCent/engnr-nsu-cpp-2021 pull request #27
Opened 2021-12-17 19:13 UTC by artemlin

2021-12-18 16:20 UTC, NikitkoCent requested changes
1 замечания/вопрос

2021-12-18 16:20 UTC, NikitkoCent commented on 1/Lab1.cpp
> +    in.close();
Эта строчка необязательна. Объясните почему.

2021-12-18 16:33 UTC, artemlin commented on 1/Lab1.cpp
> +    in.close();
Метод ifstream самостоятельно закрывает файл после использования, поэтому close  использовать необязательно

2021-12-18 17:05 UTC, NikitkoCent commented on 1/Lab1.cpp
> +    in.close();
>Метод ifstream самостоятельно закрывает файл после использования
Когда именно?

2021-12-18 17:17 UTC, artemlin commented on 1/Lab1.cpp
> +    in.close();
В конце выполнения функции (в данном случае функции main) - функция закончилась и файл закрылся

2021-12-21 15:17 UTC, NikitkoCent commented on 1/Lab1.cpp
> +    in.close();
Это не совсем точный ответ. Я ожидаю услышать объяснение, включающее в себя деструкторы.

2021-12-21 15:20 UTC, NikitkoCent commented on 1/Lab1.cpp
> +    in.close();
В любом случае удалите эту строчку и можете приходить на этап устной сдачи.

Там будьте готовы
1. Рассказать, как работает решение в целом;
2. Продемонстрировать сборку вашего приложения с нуля с помощью cmake из консоли;
3. Объяснить, зачем нужен параметр `std::ios_base::binary` в `std::ifstream in(filename, std::ios::binary)`;
4. Найти точный ответ на вопрос из этой дискуссии (про автоматическое закрытие `std::ifstream`).

2021-12-21 16:20 UTC, NikitkoCent approved these changes

2021-12-23 11:25 UTC, NikitkoCent commented
Лабораторная сдана; полный балл.

2021-12-23 11:25 UTC, closed without merging