some changes
NikitkoCent/engnr-nsu-cpp-2021 pull request #28
Opened 2021-12-18 07:14 UTC by vlad00k

2021-12-18 16:37 UTC, NikitkoCent requested changes
2 замечания/вопроса

2021-12-18 16:37 UTC, NikitkoCent commented on 1/main.cpp
> +                uint32_t r = (uint32_t)result;
С каким кодом ошибки завершится программа при попадании в этот if?

2021-12-18 16:37 UTC, NikitkoCent commented on 1/main.cpp
> +                std::cout << std::hex << result;
С каким кодом ошибки завершится программа при попадании в этот if?

2021-12-18 16:55 UTC, vlad00k commented on 1/main.cpp
> +                std::cout << std::hex << result;
вроде поправил, если правильно понял.

2021-12-18 16:55 UTC, vlad00k commented on 1/main.cpp
> +                uint32_t r = (uint32_t)result;
вроде поправил, если правильно понял.

2021-12-18 17:01 UTC, NikitkoCent requested changes
2 замечания/вопроса

2021-12-18 17:01 UTC, NikitkoCent commented on 1/main.cpp
> +                uint32_t r = (uint32_t)result;
Неправильно поняли. С каким кодом ошибки завершится программа, когда условие `if (call(fs, adler32, result) == 0)` правдиво?

2021-12-18 17:01 UTC, NikitkoCent commented on 1/main.cpp
> +                std::cout << std::hex << result;
Неправильно поняли. С каким кодом ошибки завершится программа, когда условие `!call(fs, summ64, result)` правдиво?

2021-12-18 17:18 UTC, vlad00k commented on 1/main.cpp
> +                uint32_t r = (uint32_t)result;
ну , видимо, вот так.

2021-12-18 17:23 UTC, NikitkoCent approved these changes
Больше замечаний/вопросов нет. На этапе устной сдачи будьте готовы:
1.  Собрать приложение с нуля через терминал (используя cmake);
2. Ответить, зачем нужен `std::ios_base::binary` при открытии файла.

2021-12-22 13:30 UTC, NikitkoCent commented
Лабораторная сдана; полный балл.

2021-12-22 13:30 UTC, closed without merging