Agumirov lab4
NikitkoCent/engnr-nsu-cpp-2021 pull request #30
Opened 2021-12-18 20:59 UTC by gavt45

2021-12-21 14:33 UTC, NikitkoCent requested changes
11 замечаний/вопросов

2021-12-21 14:33 UTC, OnePatchGuy commented on .github/workflows/ci.yml
> -            ${{ env.LAB_INDEX }}/build/release/
Зачем изменения в этом файле?

2021-12-21 14:33 UTC, OnePatchGuy commented on 4/dirwalker/SafeQueue.h
> +    if (q.empty()) {
Что будет, если после прохождения этого условия первым потоком, второй поток опустошит очередь?

2021-12-21 14:33 UTC, OnePatchGuy commented on 4/dirwalker/SafeQueue.h
> +    m.lock();
Почему бы здесь не воспользоваться `std::lock_guard`? В чем преимущества его использования?

2021-12-21 14:33 UTC, OnePatchGuy commented on 4/dirwalker/SafeQueue.h
> +    int length = 0;
Зачем отдельно хранить длину, если у `std::queue` есть метод size?

2021-12-21 14:33 UTC, OnePatchGuy commented on 4/dirwalker/SafeQueue.h
> +    empty = this->q.empty();
Нужно ли защищать этот код мьютексом? Почему?

2021-12-21 14:33 UTC, OnePatchGuy commented on 4/dirwalker/SafeQueue.cpp
> +//
Лишний файл?

2021-12-21 14:33 UTC, NikitkoCent commented on 4/dirwalker/SafeQueue.h
> +    return this->q.size();
Нужно ли защищать этот код мьютексом? Почему?

2021-12-21 14:33 UTC, OnePatchGuy commented on 4/dirwalker/ThreadPool.cpp
> +//
Лишний файл?

2021-12-21 14:33 UTC, OnePatchGuy commented on 4/dirwalker/ThreadPool.h
> +    task = t;
Здесь будет копия, воспользуйтесь `std::move`

2021-12-21 14:33 UTC, OnePatchGuy commented on 4/main.cpp
> +#ifdef _WIN32
Зачем это нужно?

2021-12-21 14:33 UTC, OnePatchGuy commented on 4/dirwalker/ThreadPool.h
> +        return future;
В коде результат вызова этого метода (`submit`) никак не используется. Отсюда вопросы:
1. Зачем вообще создавать std::future?
2. Следовательно, зачем вам std::packaged_task?

2021-12-21 14:34 UTC, NikitkoCent requested changes

2021-12-21 14:34 UTC, NikitkoCent commented on 4/CMakeLists.txt
> +
Если собираетесь сдавать и вторую часть лабы (про ThreadSanitizer (TSan)), то не забудьте его подключить.

2021-12-22 15:28 UTC, gavt45 commented on .github/workflows/ci.yml
> -            ${{ env.LAB_INDEX }}/build/release/
При мерджах затащил из другой ветки.

2021-12-22 15:28 UTC, gavt45 commented on 4/dirwalker/SafeQueue.h
> +    if (q.empty()) {
Гонка. Добавил lock_guard

2021-12-22 15:29 UTC, gavt45 commented on 4/dirwalker/SafeQueue.h
> +    m.lock();
Добавил. Удобно т.к не забудешь разблокировать мутекс, так же он следит за дедлоками.

2021-12-22 15:30 UTC, gavt45 commented on 4/dirwalker/SafeQueue.h
> +    empty = this->q.empty();
Может получиться гонка.

2021-12-22 15:31 UTC, gavt45 commented on 4/dirwalker/SafeQueue.h
> +    return this->q.size();
Защита от гонок

2021-12-22 15:31 UTC, gavt45 commented on 4/dirwalker/SafeQueue.h
> +    int length = 0;
Удалил

2021-12-22 15:31 UTC, gavt45 commented on 4/dirwalker/ThreadPool.cpp
> +//
Удалил

2021-12-22 15:36 UTC, gavt45 commented on 4/dirwalker/ThreadPool.h
> +        return future;
Используется в основном воркере:
```cpp
main.cpp: unsigned long long worker(ThreadPool<int> &tp, const string &file)
```
Для того, чтобы ожидать выполнения задач таким образом:
```cpp
for (auto &fut : futs) {
    sz += fut.get();
}
```

2021-12-22 15:36 UTC, gavt45 commented on 4/main.cpp
> +#ifdef _WIN32
Удалил, не использовалось.

2021-12-22 15:38 UTC, gavt45 commented on 4/dirwalker/ThreadPool.h
> +    task = t;
Понял, спасибо!

2021-12-23 07:45 UTC, NikitkoCent requested changes
Замечания/вопросы.

2021-12-23 07:45 UTC, OnePatchGuy commented on 4/dirwalker/ThreadPool.h
> +        m_notifier.notify_one();
Поток, "уснувший" в результате вызова метода `std::condition_variable::wait()` может "проснуться", даже если никакой другой поток не вызывал `std::condition_variable::notify_one()` / `std::condition_variable::notify_all()`. Такая ситуация называется "ложное пробуждение" (https://en.wikipedia.org/wiki/Spurious_wakeup).

А теперь представим следующую последовательность событий:
1. _Поток A_ внутри вашего метода `next_task()` захватил мьютекс (`std::unique_lock<std::mutex> lock{m_mutex};`)

2.  _Поток A_ внутри вашего метода `next_task()` "уснул" на вызове метода `.wait()`, при этом освободив мьютекс (так работает ожидание на условной переменной);

3. _Поток A_ внутри вашего метода `next_task()` "проснулся" _**в результате ложного пробуждения**_, автоматически обратно захватив мьютекс (так работает пробуждение на условной переменной);

4. _Поток A_ внутри вашего метода `next_task()` "осознал", что условие ожидания (`!tasks.empty() || m_stop`) еще не выполнено.

5. _Поток B_ выполнил метод `submit()`, в частности строчку `m_notifier.notify_one();`

6. _Поток A_ внутри вашего метода `next_task()` обратно "уснул" на условной переменной из-за ситуации из пункта 4;

7. _Поток B_ больше ничего не делает (так получилось, что для него "работы" больше нет).

Получается, что _Поток A_ "уснул" навечно, т.к. после его второго "засыпания" никакой другой поток не вызвал `m_notifier.notify_one()` / `m_notifier.notify_all()`. Таким образом, новая задача, которую _Поток B_ создал в пункте 5, не будет выполнена.

Требуется:
1. Исключить возможность возникновения такой ситуации (подсказка: нужно дополнительно воспользоваться вашим мьютексом `m_mutex`);
2. На этапе устной сдачи этой лабораторной быть готовым продемонстрировать понимание этой ситуации и ее решения (объяснив и то, и другое).

2021-12-23 07:45 UTC, NikitkoCent commented on 4/dirwalker/ThreadPool.h
> +        m_notifier.notify_one();
P.S. с методом `join` ситуация аналогичная

2021-12-23 07:45 UTC, NikitkoCent commented on 4/dirwalker/ThreadPool.h
> +        while (!tasks.empty()) {
Возможно, из описания лабораторной это неочевидно, но команда `:cancel` должна отменять обработку всех _уже поступивших_, но еще не обработанных до конца запросов. После ввода этой команды ожидается, что программа войдет в состояние ожидания новых запросов (как в момент сразу после запуска программы) - пользователь либо может ввести `:exit` для завершения работы, либо вводить новые запросы.

А с такой реализацией возможна ситуация, когда будут отменяться запросы, поступившие уже _после_ ввода команды `:cancel`
1. Приведите пример такой ситуации;
2. Исправьте реализацию.

2021-12-23 07:45 UTC, NikitkoCent commented on 4/dirwalker/ThreadPool.h
> +                ++m_active;
Зачем нужен этот объект? Я вижу, что он меняется, но не вижу, чтобы он хоть где-нибудь читался.

2021-12-23 07:45 UTC, NikitkoCent commented on 4/dirwalker/ThreadPool.h
> +        return tasks.next();
Что будет, если код дойдет до этой строчки из-за того, что условие `!tasks.empty() || m_stop;` выполнилось благодаря именно флагу `m_stop`?

2022-01-08 07:18 UTC, gavt45 commented on 4/dirwalker/ThreadPool.h
> +                ++m_active;
На будущее

2022-01-08 08:03 UTC, NikitkoCent submitted a review, later dismissed
Лабораторная готова к устной сдаче.

2022-01-08 10:28 UTC, NikitkoCent approved these changes

2022-01-08 10:29 UTC, NikitkoCent commented
Этап устной сдачи пройден успешно.

Лабораторная работа сдана; полный балл.

2022-01-08 10:29 UTC, closed without merging