Lab4
NikitkoCent/engnr-nsu-cpp-2021 pull request #33
Opened 2021-12-19 19:34 UTC by okm-lab

2021-12-21 14:18 UTC, NikitkoCent requested changes
15 замечаний/вопросов

2021-12-21 14:18 UTC, OnePatchGuy commented on 4/main.cpp
> +#define max(a, b) a > b ? a : b
Воспользуйтесь функцией стандартной библиотеки std::max

2021-12-21 14:18 UTC, OnePatchGuy commented on 4/main.cpp
> +void check_dir_threading(const std::string& start_dir, ThreadPool &pool, std::shared_ptr<Size> &size) {
Есть ли причина, по которой вместо std::unique_ptr используется std::shared_ptr? Если нет, объясните разницу между двумя этими видами умных указателей.

2021-12-21 14:18 UTC, OnePatchGuy commented on 4/main.cpp
> +    std::string task;
Если "задача" однозначно описывается путем к директории, почему бы явно не использовать `std::filesystem::path` вместо `std::string`?

2021-12-21 14:18 UTC, OnePatchGuy commented on 4/main.cpp
> +void check_dir_threading(const std::string& start_dir, ThreadPool &pool, std::shared_ptr<Size> &size) {
А, видимо это требование std::function на копируемость своих аргументов. Тогда просто
> объясните разницу между двумя этими видами умных указателей

2021-12-21 14:18 UTC, OnePatchGuy commented on 4/build/README.md
> -# build directory
Зачем удален этот файл?

2021-12-21 14:18 UTC, OnePatchGuy commented on .github/workflows/ci.yml
> +
Для чего нужно это изменение?

2021-12-21 14:18 UTC, OnePatchGuy commented on 3/ThreadPool.cpp
> +            tp_cond.wait(lock);
Почему бы не вынести логику ожидания непустой очереди в сам метод очереди (pop)? Кажется, это именно ее зона ответственности; к тому же, код этого метода (`thread_manager`) сразу станет несколько чище.

2021-12-21 14:18 UTC, NikitkoCent commented on 4/SafeQueue.cpp
> +    while (!sf_queue.empty()) {
у `std::queue` есть метод `clear`

2021-12-21 14:18 UTC, NikitkoCent commented on 4/ThreadPool.cpp
> +    while (!stop_cmd) {
Тип `bool` в C++ не является атомарным; соответственно, доступ к `stop_cmd` из нескольких потоков одновременно не является безопасным; посмотрите в сторону `std::atomic<bool>` или `std::atomic_flag`

2021-12-21 14:18 UTC, NikitkoCent commented on 4/ThreadPool.cpp
> +        if (tp_queue.empty()) {
Почему бы не вынести логику ожидания непустой очереди в сам метод очереди (pop)? Кажется, это именно ее зона ответственности; к тому же, код этого метода (`thread_manager`) сразу станет несколько чище.

2021-12-21 14:18 UTC, NikitkoCent commented on 4/CMakeLists.txt
> +set(CMAKE_CXX_FLAGS "-O2")
Задача установки флагов уровней оптимизации в CMake решается с помощью профилей:
* Debug - без оптимизаций;
* Release - максимальный уровень оптимизаций, нацеленных на производительность (тот самый `O2`);
* RelWithDebInfo - Release, но с дополнительной информацией, полезной для отладки;
* MinSizeRel - оптимизации, нацеленные на минимальный размер генерируемого исполняемого файла.

Выбирать нужный профиль можно с помощью свойства CMAKE_BUILD_TYPE во время генерации проекта:
```
cd build
cmake -D "CMAKE_BUILD_TYPE=Release" ..
```

2021-12-21 14:18 UTC, NikitkoCent commented on 4/ThreadPool.h
> +        auto task_ptr = std::make_shared<std::packaged_task<decltype(f(args...)) ()>>(std::bind(std::forward<F>(f), std::forward<A>(args)...));
Кажется, здесь не нужен ни std::shared_ptr, ни std::packaged_task. Почему бы просто не воспользоваться связкой std::function + std::bind?

2021-12-21 14:18 UTC, NikitkoCent commented on 3/README.md
> +# DirectorySizeChecker
1. У вас в этой ветке две директории (`3` и `4`), с почти идентичным содержимым. Пожалуйста, удалите директорию `3`.
2. Файл `4/README.md` не заполнен.

2021-12-21 14:18 UTC, NikitkoCent commented on 4/ThreadPool.cpp
> +    close();
Эта команда (`:cancel`) не должна приводить к завершению программы; она должна лишь очищать очередь задач. После этого пользователь либо может ввести `:exit` для завершения работы, либо ввести новый запрос.

2021-12-21 14:18 UTC, NikitkoCent commented on 4/CMakeLists.txt
> +add_executable(DSC main.cpp SafeQueue.h ThreadPool.cpp ThreadPool.h SafeQueue.cpp)
Если собираетесь сдавать и вторую часть лабы (про ThreadSanitizer (TSan)), то не забудьте его подключить.

2021-12-21 15:09 UTC, okm-lab commented on 4/main.cpp
> +void check_dir_threading(const std::string& start_dir, ThreadPool &pool, std::shared_ptr<Size> &size) {
shared ptr мне нужен, так как мне нужно передавать ссылку на объект во все подзадачи пула (для конкретной директории), и когда задач на эту директорию не остается, и удаляется последняя ссылка, shared ptr запускает деструктор, который выводит сообщение о размере директории. unique ptr не дает возможность передавать ссылки в несколько функций, поэтому я его не использую

2021-12-21 15:10 UTC, okm-lab commented on .github/workflows/ci.yml
> +
случайное, видимо

2021-12-21 15:13 UTC, okm-lab commented on 4/SafeQueue.cpp
> +    while (!sf_queue.empty()) {
у меня его нет

2021-12-21 15:13 UTC, okm-lab commented on 4/ThreadPool.cpp
> +    while (!stop_cmd) {
он относится только к одному потоку,  мне не нужна атомарность

2021-12-21 15:16 UTC, okm-lab commented on 4/ThreadPool.cpp
> +    close();
Чтобы очистить очередь, я останавливаю все потоки, очищаю очередь, и запускаю потоки снова... хотя потоки можно и не закрывать на самом деле, исправлю

2021-12-21 15:22 UTC, okm-lab commented on 4/SafeQueue.cpp
> +    while (!sf_queue.empty()) {
и на cppreference тоже нет, а он не врет

2021-12-21 15:31 UTC, okm-lab commented on 4/ThreadPool.h
> +        auto task_ptr = std::make_shared<std::packaged_task<decltype(f(args...)) ()>>(std::bind(std::forward<F>(f), std::forward<A>(args)...));
запаковываю, чтобы потом обернуть в лямбду, без этого нельзя обратиться к функции и будет выдаваться ошибка

2021-12-21 17:16 UTC, okm-lab commented on 3/ThreadPool.cpp
> +            tp_cond.wait(lock);
я понял, что этот фрагмент мне вообще на самом деле не нужен

2021-12-21 17:17 UTC, okm-lab commented on 3/ThreadPool.cpp
> +            tp_cond.wait(lock);
ожидание и так реализовано за счет цикла while и вовращения false из pop, если очередь пустая

2021-12-21 18:04 UTC, okm-lab commented on 4/ThreadPool.cpp
> +    while (!stop_cmd) {
А разве это является проблемой? Эта переменная здесь только читается, а не перезаписывается, если в какой-то момент времени stop_cmd == true, то цикл в любом случае завершится на следующей итерации

2021-12-21 18:05 UTC, okm-lab commented on 4/ThreadPool.cpp
> +    while (!stop_cmd) {
изменения происходят только в одном потоке - главном

2021-12-21 18:10 UTC, NikitkoCent requested changes
Вопросы/замечания

2021-12-21 18:10 UTC, OnePatchGuy commented on 4/ThreadPool.h
> +        auto task_ptr = std::make_shared<std::packaged_task<decltype(f(args...)) ()>>(std::bind(std::forward<F>(f), std::forward<A>(args)...));
Как насчет примерно такого?
```cpp
std::function<void()> wrapped = std::bind(std::forward<F>(f), std::forward<A>(args)...);
```

2021-12-21 18:10 UTC, NikitkoCent commented on 4/ThreadPool.cpp
> +    while (!stop_cmd) {
Сколько потоков исполняют метод `thread_manager`? Из какого потока вызывается метод `close()`?

2021-12-21 18:10 UTC, NikitkoCent commented on 4/build/README.md
> -# build directory
Не исправлено.

2021-12-21 18:10 UTC, NikitkoCent commented on 4/SafeQueue.cpp
> +    while (!sf_queue.empty()) {
Упс, тут уже я ошибся :)

2021-12-21 18:10 UTC, NikitkoCent commented on 4/SafeQueue.cpp
> +    if (!sf_queue.empty())  {
Без std::condition_variable в случае пустой очереди ваша программа будет исполнять холостые циклы, из-за этого будет высокое потребление CPU "на ровном месте".

2021-12-21 18:36 UTC, okm-lab commented on 4/ThreadPool.h
> +        auto task_ptr = std::make_shared<std::packaged_task<decltype(f(args...)) ()>>(std::bind(std::forward<F>(f), std::forward<A>(args)...));
это будет работать для этой задачи, но я хочу, чтобы этот тредпул был применим не только для этой задачи, и в общем случае я должен рассмотреть ещё варианты получения возврата из функции значений при помощи обычного return, для этого я запаковываю задачу

2021-12-22 11:26 UTC, okm-lab commented
>Сколько потоков исполняют метод thread_manager? Из какого потока вызывается метод close()?

close  я могу вызвать только из главного потока, когда после цикла вызываю pool.close, переменная изменяется только тогда, а остальные потоки только читают эту переменную

2021-12-22 20:01 UTC, NikitkoCent commented on 4/SafeQueue.cpp
> +        lock.unlock();
1. Это некорректное использование mutex + condition_variable: вызывать wait нужно при заблокированном мьютексе;
2. Условие sf_queue.empty() следует проверять в цикле для защиты от т.н. "ложных пробуждений" (https://en.wikipedia.org/wiki/Spurious_wakeup), примерно так:
```cpp
std::unique_lock<std::mutex> sf_lock(wait_mutex);
while (sf_queue.empty())
    cond.wait(sf_lock);
```

P.S. после такого цикла явно проверять `if (!sf_queue.empty())` уже не имеет смысла

2021-12-22 20:01 UTC, NikitkoCent commented on 4/ThreadPool.cpp
> +    while (!stop_cmd) {
Но читают эти изменения также и другие потоки.

2021-12-30 19:32 UTC, NikitkoCent commented
Первая часть лабораторной сдана - 35 баллов.

2021-12-30 19:32 UTC, closed without merging