Tboltunov lab1
NikitkoCent/engnr-nsu-cpp-2021 pull request #35
Opened 2021-12-21 14:57 UTC by Boguslave

Отлаживал и упрощал прям здесь, и вышло много коммитов. Болтунов Тимофей.

2021-12-21 15:02 UTC, NikitkoCent requested changes
1 замечание/вопрос. Если успеете разобраться до этапа устной сдачи, то можете приходить сдавать.

На этапе устной сдачи будьте готовы:
1. Рассказать, как работает решение в целом;
2. Продемонстрировать сборку вашего приложения с нуля с помощью cmake из консоли;
3. Объяснить, зачем нужен параметр `std::ios_base::binary` в `file.open(path, std::ios_base::binary)`.

2021-12-21 15:02 UTC, NikitkoCent commented on 1/.vscode/settings.json
> +{
Этот файл содержит настройки вашей IDE, которые не относятся к решению лабораторной. Его в PR быть не должно. Можете воспользоваться `git rm --cached`.

2021-12-21 15:13 UTC, Boguslave commented on 1/.vscode/settings.json
> +{
std::ios_base::binary. Так мы же файл считываем бинарный, это наподобие "rb" в питоне, я так понял

2021-12-21 16:22 UTC, NikitkoCent commented on 1/.vscode/settings.json
> +{
А что будет, если не передавать этот флаг?

2021-12-22 13:29 UTC, NikitkoCent commented
Лабораторная сдана; полный балл.

2021-12-22 13:29 UTC, closed without merging