Iuchanov lab1
NikitkoCent/engnr-nsu-cpp-2021 pull request #39
Opened 2021-12-28 14:38 UTC by uchansansan

2021-12-30 19:30 UTC, NikitkoCent requested changes
1 замечание.

2021-12-30 19:30 UTC, NikitkoCent commented on 1/main.cpp
> +uint32_t adler32(ifstream &file) {
Пожалуйста, вынесите реализации функций `adler32`, `sum64` в отдельный .cpp файл, а также объявление этих функций в отдельный заголовочный файл.

2022-01-01 09:28 UTC, uchansansan commented on 1/main.cpp
> +uint32_t adler32(ifstream &file) {
сделал

2022-01-01 17:03 UTC, NikitkoCent requested changes
Не заполнен `1/README.md` (см. общие положения о сдаче лабораторных).

2022-01-02 11:47 UTC, NikitkoCent approved these changes
Замечаний/вопросов по коду больше нет.

На этапе устной сдачи будьте готовы:
1. Рассказать, как работает решение в целом;
2. Продемонстрировать сборку вашего приложения с нуля с помощью cmake из консоли;
3. Объяснить, зачем нужен параметр `std::ios::binary` в `in.open(filename, ios::binary)`.

2022-01-05 02:28 UTC, NikitkoCent commented
Лабораторная засчитана; полный балл.

2022-01-05 02:28 UTC, closed without merging