vveselov lab2
NikitkoCent/engnr-nsu-cpp-2021 pull request #44
Opened 2022-01-04 08:10 UTC by vlad00k

2022-01-05 02:15 UTC, NikitkoCent requested changes
Вопросы/замечания.

2022-01-05 02:15 UTC, OnePatchGuy commented on 2/CommandPreprocessing.cpp
> +            command = created.Fmethod(delim_words);
Если из строк 19 или 20 вылетит исключение, то возникнет утечка памяти.
1. Объясните, что это, и в чем она заключается в вашем случае;
2. Могут ли тут помочь умные указатели? Почему?
3. Если в пункте 2 ответ положительный, то примените в вашем коде умные указатели.

2022-01-05 02:15 UTC, OnePatchGuy commented on 2/CommandPreprocessing.cpp
> +        while (std::getline(input2, str, '\n')) {
У вас фактически содержимое веток (`if (flag == 1)` - `else if` - `else`) совпадает. Подумайте, как можно избежать дублирования кода, написав функцию, которая умеет обрабатывать любые типы стримов (будь то `stringstream` или `ifstream`). Подсказка: посмотрите в сторону `std::istream`.

2022-01-05 02:15 UTC, OnePatchGuy commented on 2/calculator.hpp
> +    virtual void cmd(Context& context,  std::vector<std::string> str)=0;
Было бы лучше второй параметр (`str`) передавать не по значению, а по ссылке? Почему?

2022-01-05 02:15 UTC, OnePatchGuy commented on 2/calculator.cpp
> +    } else if (!is_number(str[1])) {
Почему нужна проверка `!is_number`?

2022-01-05 02:15 UTC, OnePatchGuy commented on 2/calculator.hpp
> +    virtual  Command *Fmethod(std::vector<std::string> vec) = 0;
Было бы лучше параметр (`vec`) передавать не по значению, а по ссылке? Почему?

2022-01-05 02:15 UTC, NikitkoCent commented on 2/calculator.cpp
> +void push::cmd(Context &context, std::vector<std::string> str) {
Пожалуйста, добавьте для этой функции тест примерно следующего содержания:
```
PUSH 10000000000000000000
PRINT
```

Ожидается, что калькулятор выбросит исключение, говорящее о переполнении (`10000000000000000000` превышает максимальное значение, которое может вместить `int64_t`).

2022-01-05 02:15 UTC, NikitkoCent commented on 2/calculator.cpp
> +        std::cout << std::to_string((int64_t) context.mystack.top()) << std::endl;
std::to_string тут лишний, std::cout и так умеет выводить объекты `int64_t`.

2022-01-05 02:15 UTC, NikitkoCent commented on 2/calculator.cpp
> +void push::cmd(Context &context, std::vector<std::string> str) {
P.S. GoogleTest предоставляет функцию `EXPECT_THROW` для проверки того, что тот или иной кусок кода действительно выбросит исключение.

2022-01-05 02:15 UTC, NikitkoCent commented on 2/tests/tests.cpp
> +#include "../calculator.hpp"
Пожалуйста, добавьте два вот таких теста:
1.
```
PUSH 853373436854
PUSH 20898131
MUL
PRINT
```

2.
```
PUSH -9223372036854775808
ABS
PRINT
```

Ожидается, что калькулятор на обоих этих тестах выбросит исключение о переполнении: в первом случае результат умножения "не влезает" в `int64_t`, во втором - модуль числа |-9223372036854775808| на единицу превышает максимальное значение `int64_t`.

2022-01-05 06:18 UTC, vlad00k commented on 2/calculator.hpp
> +    virtual void cmd(Context& context,  std::vector<std::string> str)=0;
Поскольку при передаче по ссылке копирования аргументов не происходит, то этот способ гораздо эффективнее и быстрее передачи по значению, особенно при работе с большими структурами или классами.

2022-01-05 06:20 UTC, vlad00k commented on 2/calculator.hpp
> +    virtual  Command *Fmethod(std::vector<std::string> vec) = 0;
Поскольку при передаче по ссылке копирования аргументов не происходит, то этот способ гораздо эффективнее и быстрее передачи по значению, особенно при работе с большими структурами или классами.

2022-01-05 06:28 UTC, vlad00k commented on 2/calculator.cpp
> +    } else if (!is_number(str[1])) {
Наверно можно и без нее, но так спокойнее как-то...  Вроде можно и убрать, но не уверен. Так, как сейчас здесь написано, я уверен, что сделал случаи для всех вариантов работы данного класса, пусть даже я и не могу придумать, когда оно сломается. В  общем, так спокойнее :)

2022-01-05 07:45 UTC, vlad00k commented on 2/calculator.cpp
> +    } else if (!is_number(str[1])) {
По итогу переделал немного

2022-01-05 07:45 UTC, vlad00k commented on 2/CommandPreprocessing.cpp
> +            command = created.Fmethod(delim_words);
при вылете исключения, программа перестает работать , а указатель остается, у умного указателя есть деструктор, который чистит память.

2022-01-05 07:47 UTC, vlad00k commented on 2/CommandPreprocessing.cpp
> +            command = created.Fmethod(delim_words);
но вроде бы я тут все почистил и удалил...

2022-01-05 07:48 UTC, vlad00k commented on 2/CommandPreprocessing.cpp
> +            command = created.Fmethod(delim_words);
Поэтому, я думаю, что не нада ....

2022-01-06 11:19 UTC, vlad00k commented on 2/CommandPreprocessing.cpp
> +            command = created.Fmethod(delim_words);
нада ... Исправил, теперь использую умные указатели(указыватели)

2022-01-06 23:24 UTC, NikitkoCent commented on 2/CommandPreprocessing.cpp
> +            command = created.Fmethod(delim_words);
>нада ...

Так почему все-таки нужно?

2022-01-06 23:30 UTC, NikitkoCent commented on 2/calculator.cpp
> +    } else if (!is_number(str[1])) {
Если код доходит до этой строчки, то в первом `if` функция `is_number` вернула `false`. А тут вы еще раз это зачем-то проверяете.

2022-01-06 23:32 UTC, NikitkoCent approved these changes
Остались 1 неразрешенный вопрос и 1 замечание.
Тем не менее, код готов к этапу устной сдачи.

2022-01-09 23:10 UTC, NikitkoCent commented
Лабораторная работа сдана; полный балл.

2022-01-09 23:10 UTC, closed without merging