Ashmakov lab2
NikitkoCent/engnr-nsu-cpp-2021 pull request #45
Opened 2022-01-04 20:19 UTC by ArtyomSh

2022-01-07 00:14 UTC, NikitkoCent requested changes
6 вопросов/замечаний.

2022-01-07 00:14 UTC, OnePatchGuy commented on 2/tests/CMakeFiles/2.dir/DependInfo.cmake
> +
В PR масса лишних файлов, не относящихся к решению лабораторной. Нужно их удалить.

2022-01-07 00:14 UTC, OnePatchGuy commented on 2/calc.cpp
> +        SafeAdd(first_summand, second_summand, result);
Вам нужно проверять значение, возвращаемое этой функцией. Она вернет false, если "безопасно" сложить числа не удалось.

То же самое относится и к другим используемым функциям этой библиотеки.

2022-01-07 00:14 UTC, OnePatchGuy commented on 2/calc.cpp
> +void Push::rep(const std::vector<std::string> &command_str,
Пожалуйста, добавьте для этой функции тест примерно следующего содержания:
```
PUSH 10000000000000000000
PRINT
```

Ожидается, что калькулятор выбросит исключение, говорящее о переполнении (`10000000000000000000` превышает максимальное значение, которое может вместить `int64_t`).

2022-01-07 00:14 UTC, OnePatchGuy commented on 2/tests/calc_tests.cpp
> +
Пожалуйста, добавьте два вот таких теста:
1.
```
PUSH 853373436854
PUSH 20898131
MUL
PRINT
```

2.
```
PUSH -9223372036854775808
ABS
PRINT
```

Ожидается, что калькулятор на обоих этих тестах выбросит исключение о переполнении: в первом случае результат умножения "не влезает" в `int64_t`, во втором - модуль числа |-9223372036854775808| на единицу превышает максимальное значение `int64_t`.

2022-01-07 00:14 UTC, OnePatchGuy commented on 2/calc.cpp
> +    if (args == 2) { // считывание из файла (есть название)
У вас фактически содержимое веток (`if (args == 2)` - `else if` - `else`) совпадает. Подумайте, как можно избежать дублирования кода, написав функцию, которая умеет обрабатывать любые типы стримов (будь то `stringstream` или `ifstream`). Подсказка: посмотрите в сторону `std::istream`.

2022-01-07 00:14 UTC, NikitkoCent commented on 2/main.cpp
> +#include <cstdlib>
Зачем инклюд "заворачивать" в `std`?

2022-01-07 07:20 UTC, ArtyomSh commented on 2/main.cpp
> +#include <cstdlib>
Это я когда пытался все починить сделал.

2022-01-07 21:24 UTC, ArtyomSh commented on 2/tests/CMakeFiles/2.dir/DependInfo.cmake
> +
Удалил

2022-01-07 21:24 UTC, ArtyomSh commented on 2/calc.cpp
> +        SafeAdd(first_summand, second_summand, result);
Исправил

2022-01-07 21:24 UTC, ArtyomSh commented on 2/calc.cpp
> +void Push::rep(const std::vector<std::string> &command_str,
Добавил.

2022-01-07 21:25 UTC, ArtyomSh commented on 2/tests/calc_tests.cpp
> +
Добавил.

2022-01-07 21:25 UTC, ArtyomSh commented on 2/calc.cpp
> +    if (args == 2) { // считывание из файла (есть название)
Переделал.

2022-01-08 08:15 UTC, NikitkoCent requested changes
Вопросы/замечания.

2022-01-08 08:15 UTC, NikitkoCent commented on 2/calc.cpp
> +        SafeAdd(first_summand, second_summand, result);
А зачем вы два раза складываете?

2022-01-08 08:15 UTC, NikitkoCent commented on 2/main.cpp
> +#include <cstdlib>
Все и без этого должно работать.

2022-01-08 08:17 UTC, NikitkoCent commented on 2/main.cpp
> +#include <cstdlib>
Имеется в виду, должно быть достаточно просто `#include <cstdlib>`

2022-01-09 00:40 UTC, NikitkoCent approved these changes
Лабораторная готова к этапу устной сдачи.

2022-01-09 23:11 UTC, NikitkoCent commented
Лабораторная принята (без этапа устной сдачи).

2022-01-09 23:11 UTC, closed without merging