'pam'
NikitkoCent/engnr-nsu-cpp-2021 pull request #50
Opened 2022-01-06 17:30 UTC by Nedobitaia1

2022-01-07 02:53 UTC, NikitkoCent requested changes
5 вопросов/замечаний.

2022-01-07 02:53 UTC, NikitkoCent commented on 2/.idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Директории `2/.idea` содержит файлы, не относящиеся к решению лабораторной. Таких файлов в PR быть не должно. Можете воспользоваться `git rm -r --cached 2/.idea` для удаления.

2022-01-07 02:53 UTC, NikitkoCent commented on 2/SafeInt/.appveyor.yml
> +version: '{build}'
Библиотеку `SafeInt` нужно подключить как подмодуль Git, а не простым копированием файлов этой библиотеки в репозиторий.

Если все сделаете правильно, файлы этой библиотеки должны пропасть из PR: https://github.com/NikitkoCent/engnr-nsu-cpp-2021/pull/50/files

2022-01-07 02:53 UTC, NikitkoCent commented on 2/Calc.cpp
> +    SafeAdd(se, fe, sum);
Функции арифметики `SafeAdd`, `SafeSubtract` и т.д. в случае возникновения ошибок арифметики не бросают исключение, а возвращают `false`. Добавьте обработку возвращаемого значения во всех случаях.

2022-01-07 02:53 UTC, NikitkoCent commented on 2/Calc.cpp
> +        while (getline(std::cin, stroka, '\n')) {
У вас фактически содержимое веток (`if (args == 2)` - `else`) совпадает. Подумайте, как можно избежать дублирования кода, написав функцию, которая умеет обрабатывать любые типы стримов (будь то `stringstream` или `ifstream`). Подсказка: посмотрите в сторону `std::istream`.

2022-01-07 02:53 UTC, NikitkoCent commented on 2/README.md
> +Для запуска программы:
Нет информации о программе.

2022-01-07 14:03 UTC, Nedobitaia1 commented on 2/.idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Сделано!

2022-01-08 08:50 UTC, NikitkoCent requested changes
Вопросы/замечания.

2022-01-08 08:50 UTC, NikitkoCent commented on 2/Calc.cpp
> +    SafeAdd(se, fe, sum);
Зачем вы два раза складываете?

2022-01-08 11:58 UTC, NikitkoCent submitted a review, later dismissed
Первые две части лабораторной готовы к устной сдаче.

2022-01-09 01:35 UTC, NikitkoCent approved these changes
Третья часть лабораторной готова к устной сдаче.

2022-01-09 23:08 UTC, NikitkoCent commented
Лабораторная принята (без этапа устной сдачи).

2022-01-09 23:08 UTC, closed without merging