Rgaidukov lab2
NikitkoCent/engnr-nsu-cpp-2021 pull request #51
Opened 2022-01-06 19:18 UTC by bolg4r

2022-01-07 03:29 UTC, NikitkoCent requested changes
7 вопросов/замечаний.

2022-01-07 03:29 UTC, NikitkoCent commented on 2/comm.cpp
> +            SafeMultiply(a,-1,a);
Функции арифметики `SafeMultiply`, `SafeAdd` и т.д. в случае возникновения ошибок арифметики не бросают исключение, а возвращают `false`. Добавьте обработку возвращаемого значения во всех случаях.

2022-01-07 03:29 UTC, NikitkoCent commented on 2/comm.cpp
> +        while (std::getline(test_s,command_line)) {
У вас фактически содержимое веток (`if (kind == 1)` - `if (kind == 2)` - `if (kind == 3)`) совпадает. Подумайте, как можно избежать дублирования кода, написав функцию, которая умеет обрабатывать любые типы стримов (будь то `stringstream` или `ifstream`). Подсказка: посмотрите в сторону `std::istream`.

2022-01-07 03:29 UTC, NikitkoCent commented on 2/tests/CMakeLists.txt
> +enable_testing()
`add_test` нет, из-за этого ваши тесты не прогоняются на GitHub: https://github.com/NikitkoCent/engnr-nsu-cpp-2021/runs/4734734568?check_suite_focus=true#step:5:23

2022-01-07 03:29 UTC, NikitkoCent commented on 2/tests/tests.cpp
> +
Пожалуйста, добавьте два вот таких теста:
1.
```
PUSH 853373436854
PUSH 20898131
MUL
PRINT
```

2.
```
PUSH -9223372036854775808
ABS
PRINT
```

Ожидается, что калькулятор на обоих этих тестах выбросит исключение о переполнении: в первом случае результат умножения "не влезает" в `int64_t`, во втором - модуль числа |-9223372036854775808| на единицу превышает максимальное значение `int64_t`.

P.S. воспользуйтесь `EXPECT_THROW`.

2022-01-07 03:29 UTC, NikitkoCent commented on 2/comm.h
> +    virtual void act(ContextExecution &context_execution, std::vector<std::string> str) = 0;
Было бы лучше второй параметр (`str`) передавать не по значению, а по ссылке? Почему?

2022-01-07 03:29 UTC, NikitkoCent commented on 2/comm.h
> +    Comm *obr( std::vector<std::string> commands) override;
Было бы лучше параметр `commands` передавать не по значению, а по ссылке? Почему?

2022-01-07 03:29 UTC, NikitkoCent commented on 2/comm.cpp
> +    if (is_number(str[1])) {
Что будет, если `str.size()` < 2?
Добавьте тест такого случая.

2022-01-07 09:47 UTC, bolg4r commented on 2/comm.h
> +    virtual void act(ContextExecution &context_execution, std::vector<std::string> str) = 0;
значение это новый элемент который копируется из старого, если старый изменится, то значение нет.

Ссылка лучше явно

2022-01-08 20:26 UTC, bolg4r commented
Всё исправил

2022-01-09 01:43 UTC, NikitkoCent requested changes
1 замечание.

2022-01-09 01:43 UTC, NikitkoCent commented on 2/for/CMakeFiles/3.22.1/CMakeCCompiler.cmake
> +set(CMAKE_C_COMPILER "C:/MinGW/bin/gcc.exe")
Директория-"мусор" `2/for`

2022-01-09 11:51 UTC, NikitkoCent approved these changes
Замечаний по коду больше нет; лабораторная допущена до этапа устной сдачи.

2022-01-09 23:08 UTC, NikitkoCent commented
Лабораторная принята (без этапа устной сдачи).

2022-01-09 23:08 UTC, closed without merging