Dshestakova lab2
NikitkoCent/engnr-nsu-cpp-2021 pull request #57
Opened 2022-01-07 15:00 UTC by dshestakova

Rabotaet — ne trogaem:)

2022-01-08 11:29 UTC, NikitkoCent approved these changes
5 вопросов/замечаний.

2022-01-08 11:29 UTC, NikitkoCent commented on 2/src/commands/Exceptions.cpp
> +//
Зачем этот файл?

2022-01-08 11:29 UTC, NikitkoCent commented on 2/src/commands/Command.cpp
> +        if (auto argsCommand = dynamic_pointer_cast<ArgsCommand>(command)) {
Все команды должны быть спроектированы так, чтобы:
1. Для работы с командой не нужно было знать реальный тип команды, а вы сейчас явно это узнаете , используя `dynamic_cast`;
2. Работа с любым типом команды выглядела единообразно

Иными словами, код использования должен быть примерно такой:
```cpp
shared_ptr<Command> command = get_command_by_string(strCommand, context);
command->eval(context, args);
```

2022-01-08 11:29 UTC, NikitkoCent commented on 2/src/commands/Command.cpp
> +    SafeDivide(b, a, res);
Арифметические функции `Safe...` при ошибке выполнения не выбрасывают исключение, а возвращают `false`. Вам нужно обработать эти ошибочные ситуации.

2022-01-08 11:29 UTC, NikitkoCent commented on 2/src/commands/Command.cpp
> +        int64_t value = stoi(args);
`std::stoi` преобразует строку в `int`, а `int` != `int64_t`. Воспользуйтесь `std::stoll`.

2022-01-08 11:29 UTC, NikitkoCent commented on 2/tests/tests.cpp
> +
Пожалуйста, добавьте следующие тесты:
1. ```
PUSH 853373436854
PUSH 20898131
MUL
PRINT
```

2. ```
PUSH -9223372036854775808
ABS
PRINT
```

3. ```
PUSH 10000000000000000000
PRINT
```

4. ```
PUSH -9223372036854775808
PUSH -1
DIV
PRINT
```

Ожидается, что все эти тесты должны выбросить исключение, т.к. результат вычисления превышает минимальное или максимальное значение, которое может хранить в себе `int64_t`.

P.S. воспользуйтесь `EXPECT_THROW`.

2022-01-08 11:32 UTC, NikitkoCent requested changes
5 вопросов/замечаний

2022-01-09 02:10 UTC, NikitkoCent requested changes
Замечания/вопросы.

2022-01-09 02:10 UTC, OnePatchGuy commented on 2/src/commands/Command.cpp
> +        shared_ptr<Command> command = get_command_by_string(strCommand, context);
1. В чем отличие `shared_ptr` от `unique_ptr`?
2. Что из них "дороже" в использовании?
3. Когда следует использовать первое, а когда второе?

2022-01-09 02:10 UTC, NikitkoCent commented on 2/src/commands/Command.h
> +    virtual void eval(string &args) = 0;
В чем отличие виртуального метода от обычного?
Иными словами, почему нельзя обойтись примерно такими классами без виртуальных методов:
```cpp
class Command {
    void eval(string &args) {}
};

class PlusCommand {
    void eval(string &args) {
        // implementation
    }

    // ...
};
```

2022-01-09 02:10 UTC, NikitkoCent commented on 2/src/commands/Command.h
> +    virtual ~Command() = default;
Зачем нужен виртуальный деструктор?

2022-01-09 12:36 UTC, dshestakova commented on 2/src/commands/Command.cpp
> +        shared_ptr<Command> command = get_command_by_string(strCommand, context);
unique_ptr - уникальный указатель, т.е нельзя создать два таких указателя, которые указывают на один и тот же объект.
shared_ptr - позволяет множественный ссылки, но за это мы "платим" 
по идее тут можно было и unique_ptr, но у меня не получилось сделать первый раз с ними, поэтому нашла shared_ptr

3) shared_ptr нужно использовать, когда планируется передавать указатели куда- то и нужно несколько копий этих указателей (например при реализации списка)

2022-01-09 12:38 UTC, dshestakova commented on 2/src/commands/Command.h
> +    virtual void eval(string &args) = 0;
virtual позволяет нам указать интерфейс работы с дочерними классами и он позволяет гарантировать, что функция будет принимать именно такие параметры, соответсвенно мы можем работать со всеми классами по одному интерфейсу.

2022-01-09 12:43 UTC, dshestakova commented on 2/src/commands/Command.h
> +    virtual ~Command() = default;
Тут виртуальный деструктор позволяет не реализовывать деструкторы для каждом дочернего класса, тем самым мы избавляемся от утечек памяти.

2022-01-09 12:49 UTC, NikitkoCent approved these changes
Замечаний/вопросов по коду больше нет; лабораторная работа допущена до устной сдачи.

2022-01-09 23:07 UTC, NikitkoCent commented
Лабораторная принята (без этапа устной сдачи).

2022-01-09 23:07 UTC, closed without merging