)
NikitkoCent/engnr-nsu-cpp-2021 pull request #61
Opened 2022-01-08 08:31 UTC by liskiran

2022-01-08 09:05 UTC, NikitkoCent approved these changes
`1/README.md` не заполнен.

После исправления лабораторная будет готова к этапу устной сдачи.

2022-01-08 09:05 UTC, NikitkoCent commented
А нет, тесты не проходят.

2022-01-08 09:06 UTC, NikitkoCent requested changes
Тесты не проходят.

2022-01-08 09:20 UTC, NikitkoCent requested changes

2022-01-08 09:20 UTC, NikitkoCent commented on 1/CMakeLists.txt
> +add_executable(lab1 main.cpp hash.cpp hash.h)
Не выставлены уровни предупреждений, как этого требуют общие положения о сдаче (п.4)

2022-01-08 09:47 UTC, liskiran commented on 1/CMakeLists.txt
> +add_executable(lab1 main.cpp hash.cpp hash.h)
пофиксил

2022-01-08 10:54 UTC, NikitkoCent approved these changes
Лабораторная готова к устной сдаче.

На этапе устной сдачи будьте готовы:
1. Рассказать, как работает решение в целом;
2. Продемонстрировать сборку вашего приложения с нуля с помощью cmake из консоли;
3. Объяснить, зачем нужен параметр `std::ios_base::binary` в `file.open(filename, std::ios_base::binary)`.

2022-01-09 23:07 UTC, NikitkoCent commented
Лабораторная принята (без этапа устной сдачи).

2022-01-09 23:07 UTC, closed without merging