Dpiskeeva lab2
NikitkoCent/engnr-nsu-cpp-2021 pull request #62
Opened 2022-01-08 09:08 UTC by Fossamar

2022-01-08 11:45 UTC, NikitkoCent requested changes
1 замечание.

2022-01-08 11:45 UTC, NikitkoCent commented on 2/Operations.cpp
> +            SafeDivide(val2, val1, res);
1. Функция SafeDivide в случае возникновения ошибки не выбросит исключение, а вернет `false`. Вам нужно обработать эту ошибочную ситуацию.

2. Добавьте такой тест:
```
PUSH -9223372036854775808
PUSH -1
DIV
PRINT
```
Ожидается, что все эти тесты должны выбросить исключение, т.к. результат вычисления превышает минимальное или максимальное значение, которое может хранить в себе `int64_t`.

P.S. воспользуйтесь `EXPECT_THROW`.

2022-01-09 02:21 UTC, NikitkoCent requested changes
Замечания/вопросы.

2022-01-09 02:21 UTC, NikitkoCent commented on 2/Operations.cpp
> +void Abs::command(Memory &memory) {
Добавьте такой тест:
```
PUSH -9223372036854775808
ABS
PRINT
```

Ожидается, что тест должен выбросить исключение, т.к. результат вычисления превышает максимальное значение, которое может хранить в себе `int64_t`.

P.S. воспользуйтесь `EXPECT_THROW`.

2022-01-09 02:21 UTC, NikitkoCent commented on 2/Operations.cpp
> +        std::from_chars(val.data(), val.data() + val.size(), result);
Вы не проверяете результат преобразования (могут возникать ошибки).

2022-01-09 02:21 UTC, NikitkoCent commented on 2/Operations.cpp
> +        if (ec == std::errc::result_out_of_range) {
`std::errc::result_out_of_range` не единственная ошибка, которая может возникать. Посмотрите на en.cppreference.com пример правильного использования этой функции

2022-01-09 02:21 UTC, NikitkoCent commented on 2/Operations.h
> +    virtual void
В чем отличие виртуального метода от обычного?
Иными словами, почему нельзя обойтись примерно такими классами без виртуальных методов:
```cpp
class Operation {
public:
    void command (Memory &memory) {}
};

class PlusOperation : public Operation {
public:
    void command (Memory &memory) {
        // implementation
    }

    // ...
};
```

2022-01-09 02:21 UTC, NikitkoCent commented on 2/Operations.h
> +    virtual ~Operation() = default ;
В чем отличие от виртуального деструктора от невиртуального? Зачем нужен виртуальный деструктор?

2022-01-09 12:15 UTC, Fossamar commented on 2/Operations.h
> +    virtual void
Так как мы переопределяем функцию у дочернего с помощью него. А так у нас функции семантически совпадают

2022-01-09 12:19 UTC, Fossamar commented on 2/Operations.h
> +    virtual ~Operation() = default ;
Чтобы в наследственном классе можно было сразу вызвать деструктор базового и как результат не происходит утечка памяти

2022-01-09 12:20 UTC, Fossamar commented on 2/Operations.h
> +    virtual void
То есть он будет использовать эту функцию у дочернего класса

2022-01-09 23:05 UTC, NikitkoCent approved these changes
Лабораторная принята (без этапа устной сдачи).

2022-01-09 23:07 UTC, closed without merging