A. gumirov lab1
NikitkoCent/engnr-nsu-cpp-2021 pull request #7
Opened 2021-11-09 02:04 UTC by gavt45

2021-11-13 02:04 UTC, NikitkoCent requested changes

2021-11-13 02:04 UTC, NikitkoCent commented on 1/HashCalc.cpp
> +        tmp = NTOHLL(tmp);
Этот вариант кода полагается на то, что существуют архитектуры только с little-endian и big-endian порядком байт, однако это не так - как минимум, существует также и middle-endian порядок (https://en.wikipedia.org/wiki/Endianness#Middle-endian).

Вообще в этой задаче не стоит пытаться учесть всевозможные варианты порядка байт, т.к.:
* Реализация усложняется
* Может существовать архитектура с экзотическим порядком байт, который не был предусмотрен. В таком случае программа будет выдавать некорректный результат.

Более простой и, что самое главное, универсальной реализации можно добиться с помощью битовых сдвигов: C++ гарантирует, что если к целочисленному объекту применить операцию битового сдвига, то его байты "сдвинутся", в случае сдвига влево, в направлении от младшего-к-старшему, а в случае сдвига вправо наоборот - от старшего к младшему.

При таком подходе вам также не понадобятся платформо-специфичные системные вызовы (`ntohl`, `htonl`) и соответствующие инклюды.

2021-11-13 03:04 UTC, NikitkoCent commented on 1/CMakeLists.txt
> +add_compile_options(-Wall -pedantic)
1. Вместо `add_compile_options` в современном CMake лучше пользоваться [target_compile_options](https://cmake.org/cmake/help/latest/command/target_compile_options.html) - `add_compile_options` влияет на все таргеты проекта, что обычно нежелательно.

2. Для включения макс.уровней предупреждений в разных компиляторах используются разные флаги, в GCC и Clang они к счастью совпадают, а вот у MSVC другие. Здесь нужно проверить используемый компилятор и в зависимости от этого разные флаги добавлять. Этого можно добиться примерно таким кодом:

```CMake
if (MSVC)
    target_compile_options(hasher
        PRIVATE /W4          # warnings level
        PRIVATE /WX          # treat all warnings as errors
    )
else()
    target_compile_options(hasher
        PRIVATE -Wall        # basic set of warnings
        PRIVATE -pedantic    # modern C++ inspections
        PRIVATE -Werror      # treat all warnings as errors
    )
endif()
```

2021-11-13 03:09 UTC, NikitkoCent commented on 1/HashCalc.cpp
> +uint32_t HashCalc::adler32(std::ifstream &file) {
Note: если изменить тип принимаемых объектов с `std::ifstream` на его базовый класс - `std::istream`, то функция сразу станет более гибкой.

(необязательно к исправлению)

2021-11-20 15:07 UTC, gavt45 commented on 1/HashCalc.cpp
> +        tmp = NTOHLL(tmp);
Пофиксил

2021-11-20 15:07 UTC, gavt45 commented on 1/CMakeLists.txt
> +add_compile_options(-Wall -pedantic)
Пофиксил

2021-11-20 15:07 UTC, gavt45 commented on 1/HashCalc.cpp
> +uint32_t HashCalc::adler32(std::ifstream &file) {
И это тоже пофиксил

2021-12-03 01:15 UTC, NikitkoCent commented
`README.md` не заполнен

2021-12-03 01:37 UTC, NikitkoCent commented
Чтобы сдать лабу окончательно, осталось:
1. Поправить оставшиеся замечания;
2. Рассказать мне на паре (семинаре, не лекции), как ваш код работает.

2021-12-13 14:59 UTC, NikitkoCent requested changes

2021-12-13 14:59 UTC, OnePatchGuy commented on 1/main.cpp
> +#ifdef _WIN32
Зачем это? Полагаю, уже ненужно

2021-12-13 14:59 UTC, NikitkoCent commented on 1/main.cpp
> +#ifdef _WIN32
Все еще не пофикшено

2021-12-13 14:59 UTC, NikitkoCent commented
README.md все еще не заполнено.

2021-12-14 19:26 UTC, NikitkoCent commented
Этап устной сдачи пройден успешно, осталось внести правки по замечаниям выше.

2021-12-16 04:47 UTC, gavt45 commented
Пофиксил README.md и удалил не использованные инклюды

2021-12-16 12:03 UTC, NikitkoCent approved these changes
Лабораторная сдана.

2021-12-16 12:03 UTC, closed without merging