i do it with my tears
NikitkoCent/engnr-nsu-cpp-2021 pull request #70
Opened 2022-01-30 11:28 UTC by lula025

2022-01-31 16:11 UTC, NikitkoCent requested changes
1. `3/README.md` не заполнен;
2. Замечания/вопросы.

2022-01-31 16:11 UTC, NikitkoCent commented on 3/linked_list.h
> +                        const T &operator*() const
Во всех типах итератора не хватает `operator->`.
1. Добавьте его, а также несколько тестов на его использование;
2. Объясните, для чего он нужен.

2022-01-31 16:11 UTC, NikitkoCent commented on 3/linked_list.h
> +                        T &operator*()
Добавьте тест такого содержания:
```cpp
LinkedList<int> list = {1, 2, 3};
const auto iter = list.rbegin();

ASSERT_EQ(*iter, 3);
```

2022-01-31 16:11 UTC, NikitkoCent commented on 3/linked_list.h
> +            class const_reverse_iterator
 Добавьте 3-4 теста на реверсивные итераторы, которые будут демонстрировать корректность "передвижения" по элементам списка, а также доступ к элементам.

2022-02-01 09:54 UTC, lula025 commented on 3/linked_list.h
> +                        const T &operator*() const
мы разыменовываем указатель с целью вытащить дату

2022-02-01 11:02 UTC, NikitkoCent commented on 3/linked_list.h
> +                        const T &operator*() const
Что за дата?

2022-02-01 12:20 UTC, lula025 commented on 3/linked_list.h
> +            class const_reverse_iterator
а чем плохи те тесты, что уже есть, вроде работают и нормальные?

2022-02-01 13:48 UTC, NikitkoCent commented on 3/linked_list.h
> +            class const_reverse_iterator
Не заметил их 🙃

2022-02-02 16:18 UTC, NikitkoCent approved these changes
Замечаний по коду больше нет.

2022-02-02 16:18 UTC, NikitkoCent commented
Лабораторная сдана; полный балл.

2022-02-02 16:18 UTC, closed without merging