A. gumirov lab2
NikitkoCent/engnr-nsu-cpp-2021 pull request #8
Opened 2021-11-09 02:05 UTC by gavt45

2021-11-13 03:15 UTC, NikitkoCent commented
Пожалуйста, переподключите все используемые сторонние библиотеки либо с помощью подмодулей git (https://git-scm.com/book/ru/v2/Инструменты-Git-Подмодули) либо с помощью vcpkg.

2021-11-13 03:45 UTC, NikitkoCent requested changes

2021-11-13 03:45 UTC, NikitkoCent commented on 2/CMakeLists.txt
> +add_test(google_test cpp_labs_2_test)
Перед добавлением тестов нужно вызвать функцию [enable_testing()](https://cmake.org/cmake/help/latest/command/enable_testing.html#command:enable_testing):
<img width="802" alt="image" src="https://user-images.githubusercontent.com/6972448/141604179-35aa3ce5-894c-4147-bb72-26568f0d61ec.png">

2021-11-13 03:45 UTC, NikitkoCent commented on 2/CMakeLists.txt
> +#add_compile_options(-Wall -pedantic)
Предупреждения нужно вернуть :)
В документе с общими положениями по сдаче лабораторных написано, как это правильно сделать.

2021-11-13 03:45 UTC, NikitkoCent commented on 2/CommandFactory.h
> +    Command* parseCmd(stringstream &cmd){
Реализацию методов следует вынести в `.cpp` файлы, в хедерах оставить только объявления.

2021-11-13 03:45 UTC, NikitkoCent commented on 2/CMakeLists.txt
> +set_tests_properties(google_test PROPERTIES PASS_REGULAR_EXPRESSION "[  PASSED  ]")
Зачем это нужно? Без этого что-то не работает?

2021-11-13 03:45 UTC, NikitkoCent commented on 2/CommandFactory.h
> +using namespace std;
Экспорт всего `std` считается дурным тоном.

2021-12-21 14:52 UTC, NikitkoCent requested changes
11 вопросов/замечаний

2021-12-21 14:52 UTC, OnePatchGuy commented on 2/Commands.h
> +    explicit Command(string &_args) {
Пожалуйста, разделите объявление и реализацию методов по .h и .cpp файлам соответственно.

Это касается классов не только из этого хедера.

2021-12-21 14:52 UTC, OnePatchGuy commented on 2/Commands.h
> +    virtual void exec(stack<SafeInt<int64_t>> &_stack, map<string, SafeInt<int64_t>> &m) = 0;
Несоблюден пункт из методических указаний к лабораторной:
>Содержимое стека и список (лучше ассоциативный контейнер) определенных именованных параметров передавать команде в виде специального объекта — контекста исполнения;

2021-12-21 14:52 UTC, OnePatchGuy commented on 2/Commands.h
> +    virtual ~Command() {};
Зачем здесь нужен виртуальный деструктор? Какую проблему он решает?

2021-12-21 14:52 UTC, OnePatchGuy commented on 2/main.cpp
> +using namespace std;
Это считается дурным тоном.

2021-12-21 14:52 UTC, OnePatchGuy commented on 2/main.cpp
> +    vector<Command*> cmds;
Зачем нужен этот объект?

2021-12-21 14:52 UTC, OnePatchGuy commented on 2/StackCalculator.hpp
> +            std::unique_ptr<Command> shit(CommandFactory::parseCmd(ls));
1. Что такое `std::unique_ptr` и как (в общих чертах) он работает?
2. Зачем он (`std::unique_ptr`) здесь используется?
3. Будет ли лучше сделать так, чтобы метод `CommandFactory::parseCmd` сразу возвращал объект `std::unique_ptr`, вместо "сырого" указателя? Если да, то почему?

2021-12-21 14:52 UTC, OnePatchGuy commented on 2/Commands.h
> +        if (stack.empty()) throw std::runtime_error("Empty stack on pop!");
Несоблюден пункт из методических указаний к лабораторной:
>Разработать иерархию исключений, которые команды будут выбрасывать при исполнении [...]

2021-12-21 14:52 UTC, OnePatchGuy commented on 2/CMakeLists.txt
> +#			PRIVATE -Werror      # treat all warnings as errors
Пожалуйста, отключите `-pedantic` вместо `-Werror`

2021-12-21 14:52 UTC, OnePatchGuy commented on 2/CMakeLists.txt
> +#			PRIVATE /WX          # treat all warnings as errors
Пожалуйста, верните эту опцию. У вас масса предупреждений во время сборки, вызванные не подключенными библиотеками, а вашим кодом.

2021-12-21 14:52 UTC, OnePatchGuy commented on 2/CMakeLists.txt
> +#			PRIVATE -Werror      # treat all warnings as errors
Все еще не исправлено.

2021-12-21 14:52 UTC, NikitkoCent commented on 2/Commands.h
> +            _stack.push(std::stoi(varname));
`std::stoi` возвращает int, который обычно не эквивалентен std::int64_t. Предлагаю воспользоваться `std::from_chars`

2021-12-22 15:04 UTC, gavt45 commented on 2/Commands.h
> +    virtual ~Command() {};
Т.к дальше используются указатели на наследников данного интерфейса, при этом сам указатель имеет тип базового класса, следовательно при удалении подобных объектов не происходит вызов деструктора производных классов. Происходит утечка памяти. Если сделать деструктор виртуальным, то эта проблема будет решена.

2021-12-22 15:25 UTC, gavt45 commented on 2/StackCalculator.hpp
> +            std::unique_ptr<Command> shit(CommandFactory::parseCmd(ls));
1. Умный указатель нужен здесь для удаления объекта, когда указатель выходит из зоны видимости, также его нельзя случайно копировать, а можно только переместить.
2. Чтобы автоматически чистить память от объектов уже выполненных команд.
3. Лучше возвращать `unique_ptr` т.к конструктор #2 `unqiue_ptr` (https://en.cppreference.com/w/cpp/memory/unique_ptr/unique_ptr) требует, чтобы при создании объекта не могла вывалиться ошибка. Внутри функции же она может вывалиться.

2021-12-22 18:11 UTC, NikitkoCent submitted a review, later dismissed
1 замечание. После исправления жду на этап устной сдачи.

2021-12-22 18:11 UTC, OnePatchGuy commented on 2/Commands.cpp
> +        auto res =  std::from_chars(varname.data(), varname.data() + varname.size(), converted_num);
Если вы пользуетесь std::from_chars, то:
1. Вам не нужна доп.проверка с помощью `is_number`: 
<img width="793" alt="image" src="https://user-images.githubusercontent.com/6972448/147134616-02c56253-e6ad-44b5-8c9b-6488cb752ae9.png">
Иными словами, если `res.ptr != varname.data() + varname.size()`, значит строка не целиком является числом.

2. Нужно проверить и другие типы ошибок, не только `std::errc::result_out_of_range`.

3. `converted_num` содержит результат преобразования, но вы им вообще не пользуетесь

2021-12-23 11:21 UTC, NikitkoCent approved these changes

2021-12-23 11:21 UTC, NikitkoCent commented
Лабораторная сдана; полный балл.

2021-12-23 11:21 UTC, closed without merging