dtaranets-lab1
NikitkoCent/engnr-nsu-cpp-2021 pull request #9
Opened 2021-11-10 17:53 UTC by dan-taranetc

2021-11-13 03:03 UTC, NikitkoCent requested changes

2021-11-13 03:03 UTC, OnePatchGuy commented on 1/main.cpp
> +            uint64_t contr_sum = 0;
Пожалуйста, вынесите код подсчета хешей в отдельные функции и помести их в отдельный `.cpp` файл.

2021-11-13 03:03 UTC, OnePatchGuy commented on 1/main.cpp
> +                block = (((uint64_t)ntohl((block) & 0xFFFFFFFFUL)) << 32) | ntohl((uint32_t)((block) >> 32));
Этот вариант кода полагается на то, что существуют архитектуры только с little-endian и big-endian порядком байт, однако это не так - как минимум, существует также и middle-endian порядок (https://en.wikipedia.org/wiki/Endianness#Middle-endian).

Вообще в этой задаче не стоит пытаться учесть всевозможные варианты порядка байт, т.к.:

* Реализация усложняется
* Может существовать архитектура с экзотическим порядком байт, который не был предусмотрен. В таком случае программа будет выдавать некорректный результат.

Более простой и, что самое главное, универсальной реализации можно добиться с помощью битовых сдвигов: C++ гарантирует, что если к целочисленному объекту применить операцию битового сдвига, то его байты "сдвинутся", в случае сдвига влево, в направлении от младшего-к-старшему, а в случае сдвига вправо наоборот - от старшего к младшему.

При таком подходе вам также не понадобятся платформо-специфичные системные вызовы (ntohl, htonl) и соответствующие инклюды.

2021-11-13 03:03 UTC, OnePatchGuy commented on 1/main.cpp
> +                std::cerr << help << 1 << std::endl;
1. Сообщение об ошибке неинформативно - дайте пользователю понять, в чем конкретно его ошибка в данном случае.

2. Зачем здесь дополнительно выводится число `1`?

2021-11-13 03:03 UTC, OnePatchGuy commented on 1/main.cpp
> +                std::cerr << help << 3 << std::endl;
1. Сообщение об ошибке неинформативно - помимо вывода хелпа, дайте также пользователю понять, в чем конкретно его ошибка в данном случае.

2. Зачем здесь дополнительно выводится число `3`?

2021-11-13 03:03 UTC, OnePatchGuy commented on 1/main.cpp
> +        std::cerr << help << std::endl;
Сообщение об ошибке неинформативно - помимо вывода хелпа, дайте также пользователю понять, в чем конкретно его ошибка в данном случае.

2021-11-13 03:03 UTC, OnePatchGuy commented on 1/main.cpp
> +            std::cout << help << 4 << std::endl;
Зачем здесь дополнительно выводится число `4`?

2021-11-13 03:03 UTC, OnePatchGuy commented on 1/main.cpp
> +            std::cerr << help << 5 << std::endl;
1. Сообщение об ошибке неинформативно - помимо вывода хелпа, дайте также пользователю понять, в чем конкретно его ошибка в данном случае.

2. Зачем здесь дополнительно выводится число `5`?

2021-11-13 03:03 UTC, OnePatchGuy commented on 1/main.cpp
> +        std::cerr << help << 6 << std::endl;
1. Сообщение об ошибке не отображает реальной причины того, почему программа не может продолжить работу.

2. Зачем здесь выводится число `6`?

2021-11-13 03:03 UTC, OnePatchGuy commented on 1/main.cpp
> +        std::cerr << help << 6 << std::endl;
1. Сообщение об ошибке не отображает реальной причины того, почему программа не может продолжить работу. Посмотрите в сторону [std::exception::what](https://en.cppreference.com/w/cpp/error/exception/what).

2. Зачем здесь дополнительно выводится число `6`?

2021-11-13 03:03 UTC, OnePatchGuy commented on 1/CMakeLists.txt
> +add_compile_options(-Wall -pedantic)
1. Вместо `add_compile_options` в современном CMake лучше пользоваться [target_compile_options](https://cmake.org/cmake/help/latest/command/target_compile_options.html) - `add_compile_options` влияет на все таргеты проекта, что обычно нежелательно.

2. Для включения макс.уровней предупреждений в разных компиляторах используются разные флаги, в GCC и Clang они к счастью совпадают, а вот у MSVC другие. Здесь нужно проверить используемый компилятор и в зависимости от этого разные флаги добавлять. Этого можно добиться примерно таким кодом:

```CMake
if (MSVC)
    target_compile_options(hasher
        PRIVATE /W4          # warnings level
        PRIVATE /WX          # treat all warnings as errors
    )
else()
    target_compile_options(hasher
        PRIVATE -Wall        # basic set of warnings
        PRIVATE -pedantic    # modern C++ inspections
        PRIVATE -Werror      # treat all warnings as errors
    )
endif()
```

2021-11-14 07:28 UTC, dan-taranetc commented on 1/CMakeLists.txt
> +add_compile_options(-Wall -pedantic)
Здравствуйте! Вроде бы все пофиксил.

2021-11-14 07:29 UTC, dan-taranetc commented
Здравствуйте! Вроде бы все пофиксил.

2021-11-19 08:26 UTC, dan-taranetc commented
Все поправил.

2021-11-20 00:09 UTC, NikitkoCent commented
В целом по коду все ок, правда в функции подсчета хеша sum64 ты несколько перемудрил с реализацией - есть более простой и читаемый вариант, в котором на каждой итерации из файла считывается ровно по 1 байту, затем этот байт "добавляется" (с помощью битовых операций) во временный блок. Как только в блоке оказывается 8 байт, блок прибавляется к результату.

Чтобы сдать лабу окончательно, осталось мне на паре (семинаре, не лекции) рассказать, как твой код работает.

2021-12-03 01:02 UTC, NikitkoCent commented
Лабораторная сдана; полный балл.

2021-12-03 01:02 UTC, closed without merging